In [3]:
import pandas as pd
import numpy as np
import itertools
import pymc as pm
import arviz as az

import sys
sys.path.append('../Source')
from Pipeline.build_country_comparisons import buildCountryComparisons
from Pipeline.uncertainty_metrics import computeUncertainty

alignedCountryData = pd.read_csv('../Data/Processed/alignedDataCountry.csv')
countryComparisons = buildCountryComparisons(alignedCountryData)

print(countryComparisons.shape)

c:\Users\rcuhl\miniconda3\envs\georisk\Lib\site-packages\arviz\__init__.py:50: FutureWarning:
ArviZ is undergoing a major refactor to improve flexibility and extensibility while maintaining a user-friendly interface.
Some upcoming changes may be backward incompatible.
For details and migration guidance, visit: https://python.arviz.org/en/latest/user_guide/migration_guide.html
  warn(

(232525, 6)

In [4]:
caucasusData = countryComparisons[countryComparisons['region'] == 'Caucasus and Central Asia']

caucasusWeeks = sorted(caucasusData['week'].unique())
print(len(caucasusWeeks))
print(caucasusWeeks[:5])

391
[Period('2018-01-01/2018-01-07', 'W-SUN'), Period('2018-01-08/2018-01-14', 'W-SUN'), Period('2018-01-15/2018-01-21', 'W-SUN'), Period('2018-01-22/2018-01-28', 'W-SUN'), Period('2018-01-29/2018-02-04', 'W-SUN')]

In [5]:
regionCountries = sorted(set(caucasusData['countryI']) | set(caucasusData['countryJ']))
regionIndexMap = {country: i for i, country in enumerate(regionCountries)}

nRegionCountries = len(regionCountries)
print(nRegionCountries)
print(regionCountries)

9
['Afghanistan', 'Armenia', 'Azerbaijan', 'Georgia', 'Kazakhstan', 'Kyrgyzstan', 'Tajikistan', 'Turkmenistan', 'Uzbekistan']

In [2]:
initialWeekData = caucasusData[caucasusData['week'] == caucasusWeeks[0]]

initialIndexI = initialWeekData['countryI'].map(regionIndexMap).to_numpy()
initialIndexJ = initialWeekData['countryJ'].map(regionIndexMap).to_numpy()
initialWinsI = initialWeekData['winsI'].to_numpy()
initialTotals  = initialWeekData['total'].to_numpy()

with pm.Model() as rollingModel:
    indexIData = pm.Data('indexIData', initialIndexI)
    indexJData = pm.Data('indexJData', initialIndexJ)
    winsIData = pm.Data('winsIData', initialWinsI)
    totalsData = pm.Data('totalsData', initialTotals)

    beta = pm.ZeroSumNormal('beta', sigma=1.0, shape=nRegionCountries)
    p = pm.math.sigmoid(beta[indexIData] - beta[indexJData])
    obs = pm.Binomial('obs', n=totalsData, p=p, observed=winsIData)

NameError: name 'caucasusData' is not defined

In [ ]:
# NUTS Approach

import time

weeklyResults = []
weeksSkipped = []

startTime = time.time()

for week in caucasusWeeks:
    weekData = caucasusData[caucasusData['week'] == week]

    if len(weekData) == 0:
        weeksSkipped.append(week)
        continue

    indexI = weekData['countryI'].map(regionIndexMap).to_numpy()
    indexJ = weekData['countryJ'].map(regionIndexMap).to_numpy()
    winsI = weekData['winsI'].to_numpy()
    totals = weekData['total'].to_numpy()

    with rollingModel:
        pm.set_data({
            'indexIData': indexI,
            'indexJData': indexJ,
            'winsIData': winsI,
            'totalsData': totals
        })

        trace = pm.sample(200, tune=200, target_accept=0.9, return_inferencedata=True, chains=2, cores=2, progressbar=False)

    weeklyResults.append({'week': week, 'trace': trace})

endTime = time.time()

print(f"Total time: {endTime - startTime:.1f} seconds")
print(f"Weeks fit: {len(weeklyResults)}")
print(f"Weeks skipped: {len(weeksSkipped)}")

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 14 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 15 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 13 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 13 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 13 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 15 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 15 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 14 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 14 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 13 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 13 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 13 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 13 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 13 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 13 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 13 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 13 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 13 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 13 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 13 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 10 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 13 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 15 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 15 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 15 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 14 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 13 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 13 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 13 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 14 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 14 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 14 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
The rhat statistic is larger than 1.01 for some parameters. This indicates problems during sampling. See https://arxiv.org/abs/1903.08008 for details
The effective sample size per chain is smaller than 100 for some parameters.  A higher number is needed for reliable rhat and ess computation. See https://arxiv.org/abs/1903.08008 for details
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 200 tune and 200 draw iterations (400 + 400 draws total) took 13 seconds.

KeyboardInterrupt:

In [ ]:
# ADVI approach

import time 

weeklyMetrics = []
weeksSkipped = []

startTime = time.time()

for week in caucasusWeeks:
    weekData = caucasusData[caucasusData['week'] == week]

    if len(weekData) == 0:
        weeksSkipped.append(week)
        continue

    indexI = weekData['countryI'].map(regionIndexMap).to_numpy()
    indexJ = weekData['countryJ'].map(regionIndexMap).to_numpy()
    winsI = weekData['winsI'].to_numpy()
    totals = weekData['total'].to_numpy()

    with rollingModel:
        pm.set_data({
            'indexIData': indexI,
            'indexJData': indexJ,
            'winsIData': winsI,
            'totalsData': totals
        })

        approx = pm.fit(n=20000, method='advi', progressbar=False)
        trace = approx.sample(400)

    results = computeUncertainty(trace, regionCountries)

    weeklyMetrics.append({
        'week': week,
        'region': 'Caucasus and Central Asia',
        'entropy': results['entropy'],
        'flipProbabilities': results['flipProbabilities'],
        'hdiOverlaps': results['hdiOverlaps']
    })

endTime = time.time()

print(f"Total time: {endTime - startTime:.1f} seconds")
print(f"Weeks fit: {len(weeklyMetrics)}")
print(f"Weeks skipped: {len(weeksSkipped)}")

Finished [100%]: Average Loss = 48.595
Finished [100%]: Average Loss = 61.539
Finished [100%]: Average Loss = 48.663
Finished [100%]: Average Loss = 61.672
Finished [100%]: Average Loss = 60.882
Finished [100%]: Average Loss = 63.613
Finished [100%]: Average Loss = 49.456
Finished [100%]: Average Loss = 49.96
Finished [100%]: Average Loss = 50.164
Finished [100%]: Average Loss = 72.561
Finished [100%]: Average Loss = 60.577
Finished [100%]: Average Loss = 60.089
Finished [100%]: Average Loss = 59.456
Finished [100%]: Average Loss = 75.127
Finished [100%]: Average Loss = 63.773
Finished [100%]: Average Loss = 51.667
Finished [100%]: Average Loss = 64.329
Finished [100%]: Average Loss = 73.337
Finished [100%]: Average Loss = 65.097
Finished [100%]: Average Loss = 51.327
Finished [100%]: Average Loss = 61.283
Finished [100%]: Average Loss = 64.072
Finished [100%]: Average Loss = 76.527
Finished [100%]: Average Loss = 60.577
Finished [100%]: Average Loss = 50.696
Finished [100%]: Average Loss = 50.247
Finished [100%]: Average Loss = 49.407
Finished [100%]: Average Loss = 47.671
Finished [100%]: Average Loss = 59.488
Finished [100%]: Average Loss = 66.5
Finished [100%]: Average Loss = 48.835
Finished [100%]: Average Loss = 49.95
Finished [100%]: Average Loss = 60.53
Finished [100%]: Average Loss = 36.798
Finished [100%]: Average Loss = 69.635
Finished [100%]: Average Loss = 63.041
Finished [100%]: Average Loss = 60.74
Finished [100%]: Average Loss = 61.896
Finished [100%]: Average Loss = 62.535
Finished [100%]: Average Loss = 71.845
Finished [100%]: Average Loss = 49.023
Finished [100%]: Average Loss = 58.829
Finished [100%]: Average Loss = 47.502
Finished [100%]: Average Loss = 46.077
Finished [100%]: Average Loss = 69.613
Finished [100%]: Average Loss = 44.906
Finished [100%]: Average Loss = 47.664
Finished [100%]: Average Loss = 67.707
Finished [100%]: Average Loss = 68.479
Finished [100%]: Average Loss = 56.964
Finished [100%]: Average Loss = 47.691
Finished [100%]: Average Loss = 46.808
Finished [100%]: Average Loss = 53.341
Finished [100%]: Average Loss = 53.246
Finished [100%]: Average Loss = 46.745
Finished [100%]: Average Loss = 56.329
Finished [100%]: Average Loss = 46.541
Finished [100%]: Average Loss = 46.574
Finished [100%]: Average Loss = 58.596
Finished [100%]: Average Loss = 46.067
Finished [100%]: Average Loss = 59.305
Finished [100%]: Average Loss = 66.976
Finished [100%]: Average Loss = 59.668
Finished [100%]: Average Loss = 59.191
Finished [100%]: Average Loss = 70.463
Finished [100%]: Average Loss = 67.979
Finished [100%]: Average Loss = 59.044
Finished [100%]: Average Loss = 65.822
Finished [100%]: Average Loss = 62.227
Finished [100%]: Average Loss = 60.835
Finished [100%]: Average Loss = 70.271
Finished [100%]: Average Loss = 60.566
Finished [100%]: Average Loss = 72.122
Finished [100%]: Average Loss = 73.645
Finished [100%]: Average Loss = 59.231
Finished [100%]: Average Loss = 69.507
Finished [100%]: Average Loss = 62.581
Finished [100%]: Average Loss = 58.782
Finished [100%]: Average Loss = 69.995
Finished [100%]: Average Loss = 68.392
Finished [100%]: Average Loss = 73.616
Finished [100%]: Average Loss = 72.179
Finished [100%]: Average Loss = 60.842
Finished [100%]: Average Loss = 77.994
Finished [100%]: Average Loss = 48.469
Finished [100%]: Average Loss = 69.13
Finished [100%]: Average Loss = 60.99
Finished [100%]: Average Loss = 91.219
Finished [100%]: Average Loss = 74.332
Finished [100%]: Average Loss = 73.5
Finished [100%]: Average Loss = 75.756
Finished [100%]: Average Loss = 90.295
Finished [100%]: Average Loss = 62.954
Finished [100%]: Average Loss = 75.591
Finished [100%]: Average Loss = 62.638
Finished [100%]: Average Loss = 60.938
Finished [100%]: Average Loss = 71.227
Finished [100%]: Average Loss = 62.923
Finished [100%]: Average Loss = 62.602
Finished [100%]: Average Loss = 61.987
Finished [100%]: Average Loss = 62.142
Finished [100%]: Average Loss = 60.947
Finished [100%]: Average Loss = 48.372
Finished [100%]: Average Loss = 50.002
Finished [100%]: Average Loss = 66.334
Finished [100%]: Average Loss = 58.881
Finished [100%]: Average Loss = 61.679
Finished [100%]: Average Loss = 72.265
Finished [100%]: Average Loss = 62.268
Finished [100%]: Average Loss = 48.804
Finished [100%]: Average Loss = 59.027
Finished [100%]: Average Loss = 62.644
Finished [100%]: Average Loss = 59.366
Finished [100%]: Average Loss = 72.115
Finished [100%]: Average Loss = 62.213
Finished [100%]: Average Loss = 48.142
Finished [100%]: Average Loss = 53.727
Finished [100%]: Average Loss = 66.279
Finished [100%]: Average Loss = 42.882
Finished [100%]: Average Loss = 45.634
Finished [100%]: Average Loss = 53.614
Finished [100%]: Average Loss = 44.182
Finished [100%]: Average Loss = 53.832
Finished [100%]: Average Loss = 80.613
Finished [100%]: Average Loss = 69.606
Finished [100%]: Average Loss = 71.683
Finished [100%]: Average Loss = 81.825
Finished [100%]: Average Loss = 58.708
Finished [100%]: Average Loss = 86.383
Finished [100%]: Average Loss = 62.16
Finished [100%]: Average Loss = 69.53
Finished [100%]: Average Loss = 64.285
Finished [100%]: Average Loss = 63.275
Finished [100%]: Average Loss = 64.955
Finished [100%]: Average Loss = 74.703
Finished [100%]: Average Loss = 76.431
Finished [100%]: Average Loss = 84.514
Finished [100%]: Average Loss = 64.013
Finished [100%]: Average Loss = 75.74
Finished [100%]: Average Loss = 85.244
Finished [100%]: Average Loss = 60.909
Finished [100%]: Average Loss = 64.379
Finished [100%]: Average Loss = 83.615
Finished [100%]: Average Loss = 71.974
Finished [100%]: Average Loss = 74.057
Finished [100%]: Average Loss = 74.074
Finished [100%]: Average Loss = 61.434
Finished [100%]: Average Loss = 72.86
Finished [100%]: Average Loss = 74.229
Finished [100%]: Average Loss = 63.594
Finished [100%]: Average Loss = 53.435
Finished [100%]: Average Loss = 55.805
Finished [100%]: Average Loss = 54.603
Finished [100%]: Average Loss = 58.805
Finished [100%]: Average Loss = 57.909
Finished [100%]: Average Loss = 53.636
Finished [100%]: Average Loss = 51.719
Finished [100%]: Average Loss = 50.329
Finished [100%]: Average Loss = 57.099
Finished [100%]: Average Loss = 55.769
Finished [100%]: Average Loss = 68.633
Finished [100%]: Average Loss = 59.481
Finished [100%]: Average Loss = 59.984
Finished [100%]: Average Loss = 66.121
Finished [100%]: Average Loss = 57.763
Finished [100%]: Average Loss = 68.764
Finished [100%]: Average Loss = 58.182
Finished [100%]: Average Loss = 58.729
Finished [100%]: Average Loss = 53.506
Finished [100%]: Average Loss = 52.891
Finished [100%]: Average Loss = 60.622
Finished [100%]: Average Loss = 58.679
Finished [100%]: Average Loss = 60.772
Finished [100%]: Average Loss = 74.966
Finished [100%]: Average Loss = 55.759
Finished [100%]: Average Loss = 60.199
Finished [100%]: Average Loss = 70.933
Finished [100%]: Average Loss = 72.238
Finished [100%]: Average Loss = 60.212
Finished [100%]: Average Loss = 41.59
Finished [100%]: Average Loss = 57.396
Finished [100%]: Average Loss = 65.115
Finished [100%]: Average Loss = 54.525
Finished [100%]: Average Loss = 57.365
Finished [100%]: Average Loss = 66.695
Finished [100%]: Average Loss = 53.521
Finished [100%]: Average Loss = 64.113
Finished [100%]: Average Loss = 56.937
Finished [100%]: Average Loss = 54.783
Finished [100%]: Average Loss = 52.503
Finished [100%]: Average Loss = 50.95
Finished [100%]: Average Loss = 47.104
Finished [100%]: Average Loss = 49.358
Finished [100%]: Average Loss = 54.398
Finished [100%]: Average Loss = 59.564
Finished [100%]: Average Loss = 56.64
Finished [100%]: Average Loss = 47.45
Finished [100%]: Average Loss = 49.709
Finished [100%]: Average Loss = 36.132
Finished [100%]: Average Loss = 43.632
Finished [100%]: Average Loss = 46.859
Finished [100%]: Average Loss = 47.399
Finished [100%]: Average Loss = 65.339
Finished [100%]: Average Loss = 59.307
Finished [100%]: Average Loss = 61.294
Finished [100%]: Average Loss = 51.113
Finished [100%]: Average Loss = 46.883
Finished [100%]: Average Loss = 43.026
Finished [100%]: Average Loss = 48.168
Finished [100%]: Average Loss = 45.89
Finished [100%]: Average Loss = 61.197
Finished [100%]: Average Loss = 47.084
Finished [100%]: Average Loss = 60.554
Finished [100%]: Average Loss = 49.943
Finished [100%]: Average Loss = 48.722
Finished [100%]: Average Loss = 53.834
Finished [100%]: Average Loss = 51.465
Finished [100%]: Average Loss = 50.245
Finished [100%]: Average Loss = 63.925
Finished [100%]: Average Loss = 45.976
Finished [100%]: Average Loss = 45.495
Finished [100%]: Average Loss = 38.604
Finished [100%]: Average Loss = 49.4
Finished [100%]: Average Loss = 48.123
Finished [100%]: Average Loss = 54.877
Finished [100%]: Average Loss = 48.981
Finished [100%]: Average Loss = 52.438
Finished [100%]: Average Loss = 68.426
Finished [100%]: Average Loss = 66.455
Finished [100%]: Average Loss = 57.127
Finished [100%]: Average Loss = 61.966
Finished [100%]: Average Loss = 57.271
Finished [100%]: Average Loss = 62.456
Finished [100%]: Average Loss = 52.42
Finished [100%]: Average Loss = 48.378
Finished [100%]: Average Loss = 47.415
Finished [100%]: Average Loss = 44.08
Finished [100%]: Average Loss = 43.978
Finished [100%]: Average Loss = 46.745
Finished [100%]: Average Loss = 48.523
Finished [100%]: Average Loss = 49.187
Finished [100%]: Average Loss = 50.383
Finished [100%]: Average Loss = 49.757
Finished [100%]: Average Loss = 56.537
Finished [100%]: Average Loss = 44.697
Finished [100%]: Average Loss = 75.341
Finished [100%]: Average Loss = 60.391
Finished [100%]: Average Loss = 46.793
Finished [100%]: Average Loss = 38.897
Finished [100%]: Average Loss = 52.816
Finished [100%]: Average Loss = 39.274
Finished [100%]: Average Loss = 43.349
Finished [100%]: Average Loss = 32.543
Finished [100%]: Average Loss = 47.002
Finished [100%]: Average Loss = 46.805
Finished [100%]: Average Loss = 51.34
Finished [100%]: Average Loss = 38.722
Finished [100%]: Average Loss = 46.232
Finished [100%]: Average Loss = 48.967
Finished [100%]: Average Loss = 58.444
Finished [100%]: Average Loss = 52.888
Finished [100%]: Average Loss = 41.366
Finished [100%]: Average Loss = 42.852
Finished [100%]: Average Loss = 44.915
Finished [100%]: Average Loss = 43.643
Finished [100%]: Average Loss = 54.1
Finished [100%]: Average Loss = 41.757
Finished [100%]: Average Loss = 44.007
Finished [100%]: Average Loss = 46.325
Finished [100%]: Average Loss = 45.619
Finished [100%]: Average Loss = 64.663
Finished [100%]: Average Loss = 56.462
Finished [100%]: Average Loss = 51.388
Finished [100%]: Average Loss = 49.751
Finished [100%]: Average Loss = 43.257
Finished [100%]: Average Loss = 49.561
Finished [100%]: Average Loss = 35.263
Finished [100%]: Average Loss = 67.054
Finished [100%]: Average Loss = 34.771
Finished [100%]: Average Loss = 45.388
Finished [100%]: Average Loss = 42.365
Finished [100%]: Average Loss = 51.355
Finished [100%]: Average Loss = 46.084
Finished [100%]: Average Loss = 48.991
Finished [100%]: Average Loss = 46.03
Finished [100%]: Average Loss = 51.829
Finished [100%]: Average Loss = 32.891
Finished [100%]: Average Loss = 42.489
Finished [100%]: Average Loss = 50.169
Finished [100%]: Average Loss = 45.248
Finished [100%]: Average Loss = 44.617
Finished [100%]: Average Loss = 43.696
Finished [100%]: Average Loss = 34.174
Finished [100%]: Average Loss = 49.901
Finished [100%]: Average Loss = 47.582
Finished [100%]: Average Loss = 44.166
Finished [100%]: Average Loss = 38.579
Finished [100%]: Average Loss = 47.217
Finished [100%]: Average Loss = 53.65
Finished [100%]: Average Loss = 46.754
Finished [100%]: Average Loss = 41.709
Finished [100%]: Average Loss = 42.105
Finished [100%]: Average Loss = 41.158
Finished [100%]: Average Loss = 31.129
Finished [100%]: Average Loss = 41.079
Finished [100%]: Average Loss = 30.544
Finished [100%]: Average Loss = 37.271
Finished [100%]: Average Loss = 40.05
Finished [100%]: Average Loss = 32.486
Finished [100%]: Average Loss = 31.333
Finished [100%]: Average Loss = 42.735
Finished [100%]: Average Loss = 37.141
Finished [100%]: Average Loss = 34.474
Finished [100%]: Average Loss = 25.548
Finished [100%]: Average Loss = 30.188
Finished [100%]: Average Loss = 37.844
Finished [100%]: Average Loss = 35.426
Finished [100%]: Average Loss = 31.164
Finished [100%]: Average Loss = 31.185
Finished [100%]: Average Loss = 37.486
Finished [100%]: Average Loss = 41.38
Finished [100%]: Average Loss = 36.934
Finished [100%]: Average Loss = 42.704
Finished [100%]: Average Loss = 43.464
Finished [100%]: Average Loss = 35.249
Finished [100%]: Average Loss = 28.833
Finished [100%]: Average Loss = 55.699
Finished [100%]: Average Loss = 53.968
Finished [100%]: Average Loss = 46.072
Finished [100%]: Average Loss = 46.116
Finished [100%]: Average Loss = 28.433
Finished [100%]: Average Loss = 46.393
Finished [100%]: Average Loss = 59.262
Finished [100%]: Average Loss = 53.025
Finished [100%]: Average Loss = 33.345
Finished [100%]: Average Loss = 33.011
Finished [100%]: Average Loss = 54.515
Finished [100%]: Average Loss = 47.97
Finished [100%]: Average Loss = 45.728
Finished [100%]: Average Loss = 39.982
Finished [100%]: Average Loss = 23.891
Finished [100%]: Average Loss = 42.712
Finished [100%]: Average Loss = 38.987
Finished [100%]: Average Loss = 36.339
Finished [100%]: Average Loss = 27.913
Finished [100%]: Average Loss = 28.367
Finished [100%]: Average Loss = 37.42
Finished [100%]: Average Loss = 36.666
Finished [100%]: Average Loss = 31.518
Finished [100%]: Average Loss = 40.11
Finished [100%]: Average Loss = 32.926
Finished [100%]: Average Loss = 36.579
Finished [100%]: Average Loss = 36.156
Finished [100%]: Average Loss = 38.707
Finished [100%]: Average Loss = 36.339
Finished [100%]: Average Loss = 38.758
Finished [100%]: Average Loss = 40.359
Finished [100%]: Average Loss = 31.584
Finished [100%]: Average Loss = 44.559
Finished [100%]: Average Loss = 51.705
Finished [100%]: Average Loss = 31.258
Finished [100%]: Average Loss = 35.294
Finished [100%]: Average Loss = 32.354
Finished [100%]: Average Loss = 40.14
Finished [100%]: Average Loss = 40.501
Finished [100%]: Average Loss = 39.942
Finished [100%]: Average Loss = 49.762
Finished [100%]: Average Loss = 46.464
Finished [100%]: Average Loss = 36.424
Finished [100%]: Average Loss = 43.144
Finished [100%]: Average Loss = 43.959
Finished [100%]: Average Loss = 45.151
Finished [100%]: Average Loss = 45.896
Finished [100%]: Average Loss = 32.896
Finished [100%]: Average Loss = 47.921
Finished [100%]: Average Loss = 38.283
Finished [100%]: Average Loss = 35.048
Finished [100%]: Average Loss = 42.256
Finished [100%]: Average Loss = 34.411
Finished [100%]: Average Loss = 46.569
Finished [100%]: Average Loss = 44.584
Finished [100%]: Average Loss = 40.835
Finished [100%]: Average Loss = 44.105
Finished [100%]: Average Loss = 32.725
Finished [100%]: Average Loss = 41.619
Finished [100%]: Average Loss = 43.381
Finished [100%]: Average Loss = 33.585
Finished [100%]: Average Loss = 32.461
Finished [100%]: Average Loss = 22.44
Finished [100%]: Average Loss = 43.716
Finished [100%]: Average Loss = 25.195

Total time: 961.0 seconds
Weeks fit: 391
Weeks skipped: 0

In [ ]:
weeklyMetricsDF = pd.DataFrame(weeklyMetrics)
print(weeklyMetricsDF[['week', 'entropy']].describe())
print(weeklyMetricsDF[['week', 'entropy']].sort_values('entropy', ascending=False).head(10))

          entropy
count  391.000000
mean     4.256846
std      1.168268
min      1.135404
25%      3.393984
50%      4.373560
75%      5.335824
max      5.942944
                      week   entropy
390  2025-06-23/2025-06-29  5.942944
388  2025-06-09/2025-06-15  5.905671
304  2023-10-30/2023-11-05  5.897890
330  2024-04-29/2024-05-05  5.877945
248  2022-10-03/2022-10-09  5.866239
317  2024-01-29/2024-02-04  5.859308
292  2023-08-07/2023-08-13  5.853226
368  2025-01-20/2025-01-26  5.849760
306  2023-11-13/2023-11-19  5.837205
350  2024-09-16/2024-09-22  5.833740

In [ ]:
weeklyMetricsDF.to_csv('../Data/Processed/weeklyUncertaintyCaucasusCA_raw.csv', index=False)
print(weeklyMetricsDF.shape)

(391, 5)

In [ ]:
weeklyMetricsDF = pd.read_csv('../Data/Processed/weeklyUncertaintyCaucasusCA_raw.csv')

lowestEntropyWeek = weeklyMetricsDF.sort_values('entropy').iloc[0]['week']
highEntropyWeek1 = '2025-06-23/2025-06-29'
highEntropyWeek2 = '2023-10-30/2023-11-05'

testWeeksValidation = [lowestEntropyWeek, highEntropyWeek1, highEntropyWeek2]
print(testWeeksValidation)

['2020-06-15/2020-06-21', '2025-06-23/2025-06-29', '2023-10-30/2023-11-05']

In [ ]:
nutsValidation = []

for week in testWeeksValidation:
    weekPeriod = pd.Period(week, freq='W-SUN')
    weekData = caucasusData[caucasusData['week'] == weekPeriod]

    indexI = weekData['countryI'].map(regionIndexMap).to_numpy()
    indexJ = weekData['countryJ'].map(regionIndexMap).to_numpy()
    winsI = weekData['winsI'].to_numpy()
    totals = weekData['total'].to_numpy()

    with rollingModel:
        pm.set_data({
            'indexIData': indexI,
            'indexJData': indexJ,
            'winsIData': winsI,
            'totalsData': totals
        })

        trace = pm.sample(500, tune=500, target_accept=0.9, return_inferencedata=True, chains=2, cores=2, progressbar=False)

    results = computeUncertainty(trace, regionCountries)
    nutsValidation.append({'week': week, 'entropy': results['entropy']})

    print(f"{week}: NUTS entropy = {results['entropy']:.3f}")

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 500 tune and 500 draw iterations (1_000 + 1_000 draws total) took 10 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
c:\Users\rcuhl\miniconda3\envs\georisk\Lib\site-packages\threadpoolctl.py:1226: RuntimeWarning:
Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
the same time. Both libraries are known to be incompatible and this
can cause random crashes or deadlocks on Linux when loaded in the
same Python program.
Using threadpoolctl may cause crashes or deadlocks. For more
information and possible workarounds, please see
    https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

  warnings.warn(msg, RuntimeWarning)
Initializing NUTS using jitter+adapt_diag...

2020-06-15/2020-06-21: NUTS entropy = 1.000

Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 500 tune and 500 draw iterations (1_000 + 1_000 draws total) took 11 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics
c:\Users\rcuhl\miniconda3\envs\georisk\Lib\site-packages\threadpoolctl.py:1226: RuntimeWarning:
Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
the same time. Both libraries are known to be incompatible and this
can cause random crashes or deadlocks on Linux when loaded in the
same Python program.
Using threadpoolctl may cause crashes or deadlocks. For more
information and possible workarounds, please see
    https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

  warnings.warn(msg, RuntimeWarning)
Initializing NUTS using jitter+adapt_diag...

2025-06-23/2025-06-29: NUTS entropy = 6.802

Multiprocess sampling (2 chains in 2 jobs)
NUTS: [beta]
Sampling 2 chains for 500 tune and 500 draw iterations (1_000 + 1_000 draws total) took 10 seconds.
We recommend running at least 4 chains for robust computation of convergence diagnostics

2023-10-30/2023-11-05: NUTS entropy = 6.610

In [ ]:
comparison = weeklyMetricsDF[weeklyMetricsDF['week'].isin(testWeeksValidation)][['week', 'entropy']]
comparison = comparison.rename(columns={'entropy': 'adviEntropy'})

nutsDF = pd.DataFrame(nutsValidation).rename(columns={'entropy': 'nutsEntropy'})
comparison = comparison.merge(nutsDF, on='week')

print(comparison)

                    week  adviEntropy  nutsEntropy
0  2020-06-15/2020-06-21     1.135404     0.999642
1  2023-10-30/2023-11-05     5.897890     6.609835
2  2025-06-23/2025-06-29     5.942944     6.802213

In [ ]:
weeklyMetricsDF.head()

,week,region,entropy,flipProbabilities,hdiOverlaps
0,2018-01-01/2018-01-07,Caucasus and Central Asia,4.175930,"{'Afghanistan over Armenia': np.float64(1.0), ...","{'Afghanistan vs Armenia': np.False_, 'Afghani..."
1,2018-01-08/2018-01-14,Caucasus and Central Asia,3.396296,"{'Afghanistan over Armenia': np.float64(1.0), ...","{'Afghanistan vs Armenia': np.False_, 'Afghani..."
2,2018-01-15/2018-01-21,Caucasus and Central Asia,3.535702,"{'Afghanistan over Armenia': np.float64(1.0), ...","{'Afghanistan vs Armenia': np.False_, 'Afghani..."
3,2018-01-22/2018-01-28,Caucasus and Central Asia,2.841213,"{'Afghanistan over Armenia': np.float64(1.0), ...","{'Afghanistan vs Armenia': np.False_, 'Afghani..."
4,2018-01-29/2018-02-04,Caucasus and Central Asia,3.116704,"{'Afghanistan over Armenia': np.float64(1.0), ...","{'Afghanistan vs Armenia': np.False_, 'Afghani..."

In [16]:
import re

def parseMetricDict(value):
    if not isinstance(value, str):
        return value
    cleaned = re.sub(r'np\.float64\(([^)]+)\)', r'\1', value)
    cleaned = cleaned.replace('np.False_', 'False').replace('np.True_', 'True')
    return ast.literal_eval(cleaned)

In [ ]:
import ast 

longData = []

for _, row in weeklyMetricsDF.iterrows(): 
    week = row['week']
    region = row['region']
    entropy = row['entropy']

    flipProbs = parseMetricDict(row['flipProbabilities'])
    hdiOverlaps = parseMetricDict(row['hdiOverlaps'])

    for pairLabel, flipProb in flipProbs.items(): 
        countryI, countryJ = pairLabel.split(' over ')
        overlap = hdiOverlaps.get(f'{countryI} vs {countryJ}', None)

        longData.append({
            'week': week,
            'region': region,
            'entropy': entropy,
            'countryI': countryI,
            'countryJ': countryJ,
            'flipProbability': flipProb,
            'hdiOverlap': overlap
        })

longFormDF = pd.DataFrame(longData)
print(longFormDF.shape)
longFormDF.head()

(14076, 7)

,week,region,entropy,countryI,countryJ,flipProbability,hdiOverlap
0,2018-01-01/2018-01-07,Caucasus and Central Asia,4.17593,Afghanistan,Armenia,1.00,False
1,2018-01-01/2018-01-07,Caucasus and Central Asia,4.17593,Afghanistan,Azerbaijan,0.58,True
2,2018-01-01/2018-01-07,Caucasus and Central Asia,4.17593,Afghanistan,Georgia,1.00,False
3,2018-01-01/2018-01-07,Caucasus and Central Asia,4.17593,Afghanistan,Kazakhstan,1.00,False
4,2018-01-01/2018-01-07,Caucasus and Central Asia,4.17593,Afghanistan,Kyrgyzstan,1.00,False

In [ ]:
longFormDF.to_csv('../Data/Processed/weeklyUncertaintyCaucasusCA.csv', index=False)
print(longFormDF.shape)

(14076, 7)

In [ ]:
middleEastData = countryComparisons[countryComparisons['region'] == 'Middle East']

middleEastCountries = sorted(set(middleEastData['countryI']) | set(middleEastData['countryJ']))
middleEastIndexMap = {country: i for i, country in enumerate(middleEastCountries)}
nMiddleEastCountries = len(middleEastCountries)

middleEastWeeks = sorted(middleEastData['week'].unique())

print(nMiddleEastCountries)
print(len(middleEastWeeks))

13
391

In [ ]:
initialWeekData = middleEastData[middleEastData['week'] == middleEastWeeks[0]]

initialIndexI = initialWeekData['countryI'].map(middleEastIndexMap).to_numpy()
initialIndexJ = initialWeekData['countryJ'].map(middleEastIndexMap).to_numpy()
initialWinsI = initialWeekData['winsI'].to_numpy()
initialTotals  = initialWeekData['total'].to_numpy()

with pm.Model() as rollingModelME:
    indexIData = pm.Data('indexIData', initialIndexI)
    indexJData = pm.Data('indexJData', initialIndexJ)
    winsIData = pm.Data('winsIData', initialWinsI)
    totalsData = pm.Data('totalsData', initialTotals)

    beta = pm.ZeroSumNormal('beta', sigma=1.0, shape=nMiddleEastCountries)
    p = pm.math.sigmoid(beta[indexIData] - beta[indexJData])
    obs = pm.Binomial('obs', n=totalsData, p=p, observed=winsIData)

In [ ]:
import time

weeklyMetricsME = []
weeksSkippedME = []

startTime = time.time()

for week in middleEastWeeks:
    weekData = middleEastData[middleEastData['week'] == week]

    if len(weekData) == 0:
        weeksSkippedME.append(week)
        continue

    indexI = weekData['countryI'].map(middleEastIndexMap).to_numpy()
    indexJ = weekData['countryJ'].map(middleEastIndexMap).to_numpy()
    winsI = weekData['winsI'].to_numpy()
    totals = weekData['total'].to_numpy()

    with rollingModelME:
        pm.set_data({
            'indexIData': indexI,
            'indexJData': indexJ,
            'winsIData': winsI,
            'totalsData': totals
        })

        approx = pm.fit(n=20000, method='advi', progressbar=False)
        trace = approx.sample(400)

    results = computeUncertainty(trace, middleEastCountries)

    weeklyMetricsME.append({
        'week': week,
        'region': 'Middle East',
        'entropy': results['entropy'],
        'flipProbabilities': results['flipProbabilities'],
        'hdiOverlaps': results['hdiOverlaps']
    })

endTime = time.time()

print(f"Total time: {endTime - startTime:.1f} seconds")
print(f"Weeks fit: {len(weeklyMetricsME)}")
print(f"Weeks skipped: {len(weeksSkippedME)}")

Finished [100%]: Average Loss = 138.68
Finished [100%]: Average Loss = 168.35
Finished [100%]: Average Loss = 170.04
Finished [100%]: Average Loss = 171.02
Finished [100%]: Average Loss = 175.42
Finished [100%]: Average Loss = 174.92
Finished [100%]: Average Loss = 173.48
Finished [100%]: Average Loss = 169.81
Finished [100%]: Average Loss = 162.58
Finished [100%]: Average Loss = 170.7
Finished [100%]: Average Loss = 173.92
Finished [100%]: Average Loss = 167.65
Finished [100%]: Average Loss = 157.88
Finished [100%]: Average Loss = 178.31
Finished [100%]: Average Loss = 173.13
Finished [100%]: Average Loss = 168.89
Finished [100%]: Average Loss = 167.95
Finished [100%]: Average Loss = 165.38
Finished [100%]: Average Loss = 188.79
Finished [100%]: Average Loss = 197.09
Finished [100%]: Average Loss = 167.81
Finished [100%]: Average Loss = 171.8
Finished [100%]: Average Loss = 169.02
Finished [100%]: Average Loss = 162.18
Finished [100%]: Average Loss = 161.48
Finished [100%]: Average Loss = 168.37
Finished [100%]: Average Loss = 160.48
Finished [100%]: Average Loss = 163.34
Finished [100%]: Average Loss = 167.83
Finished [100%]: Average Loss = 168.43
Finished [100%]: Average Loss = 161.51
Finished [100%]: Average Loss = 165.45
Finished [100%]: Average Loss = 164.56
Finished [100%]: Average Loss = 146.84
Finished [100%]: Average Loss = 160.26
Finished [100%]: Average Loss = 180.89
Finished [100%]: Average Loss = 167.17
Finished [100%]: Average Loss = 157.1
Finished [100%]: Average Loss = 164.3
Finished [100%]: Average Loss = 159.09
Finished [100%]: Average Loss = 161.95
Finished [100%]: Average Loss = 165.18
Finished [100%]: Average Loss = 153.96
Finished [100%]: Average Loss = 157.86
Finished [100%]: Average Loss = 156.81
Finished [100%]: Average Loss = 164.71
Finished [100%]: Average Loss = 154.57
Finished [100%]: Average Loss = 167.31
Finished [100%]: Average Loss = 164.94
Finished [100%]: Average Loss = 161.05
Finished [100%]: Average Loss = 161.02
Finished [100%]: Average Loss = 155.67
Finished [100%]: Average Loss = 154.69
Finished [100%]: Average Loss = 172.84
Finished [100%]: Average Loss = 176.9
Finished [100%]: Average Loss = 175.1
Finished [100%]: Average Loss = 158.62
Finished [100%]: Average Loss = 156.22
Finished [100%]: Average Loss = 163.43
Finished [100%]: Average Loss = 166.81
Finished [100%]: Average Loss = 162.42
Finished [100%]: Average Loss = 169.25
Finished [100%]: Average Loss = 185
Finished [100%]: Average Loss = 162
Finished [100%]: Average Loss = 176.55
Finished [100%]: Average Loss = 156.63
Finished [100%]: Average Loss = 171.89
Finished [100%]: Average Loss = 156.67
Finished [100%]: Average Loss = 198.66
Finished [100%]: Average Loss = 187.52
Finished [100%]: Average Loss = 169.79
Finished [100%]: Average Loss = 168.42
Finished [100%]: Average Loss = 178.72
Finished [100%]: Average Loss = 168.32
Finished [100%]: Average Loss = 151.27
Finished [100%]: Average Loss = 180.77
Finished [100%]: Average Loss = 162.13
Finished [100%]: Average Loss = 188.23
Finished [100%]: Average Loss = 162.33
Finished [100%]: Average Loss = 174.73
Finished [100%]: Average Loss = 160.88
Finished [100%]: Average Loss = 175.13
Finished [100%]: Average Loss = 166.22
Finished [100%]: Average Loss = 175.19
Finished [100%]: Average Loss = 154.38
Finished [100%]: Average Loss = 160.35
Finished [100%]: Average Loss = 164.16
Finished [100%]: Average Loss = 161.54
Finished [100%]: Average Loss = 174.69
Finished [100%]: Average Loss = 157.54
Finished [100%]: Average Loss = 177.39
Finished [100%]: Average Loss = 160.88
Finished [100%]: Average Loss = 162.02
Finished [100%]: Average Loss = 147.02
Finished [100%]: Average Loss = 166.68
Finished [100%]: Average Loss = 169.09
Finished [100%]: Average Loss = 190.11
Finished [100%]: Average Loss = 193.35
Finished [100%]: Average Loss = 173.18
Finished [100%]: Average Loss = 149.17
Finished [100%]: Average Loss = 176.19
Finished [100%]: Average Loss = 166.08
Finished [100%]: Average Loss = 150.65
Finished [100%]: Average Loss = 160.53
Finished [100%]: Average Loss = 159.64
Finished [100%]: Average Loss = 158.74
Finished [100%]: Average Loss = 166.97
Finished [100%]: Average Loss = 163.26
Finished [100%]: Average Loss = 173.27
Finished [100%]: Average Loss = 169.05
Finished [100%]: Average Loss = 169.84
Finished [100%]: Average Loss = 161.81
Finished [100%]: Average Loss = 165.38
Finished [100%]: Average Loss = 180.86
Finished [100%]: Average Loss = 153.45
Finished [100%]: Average Loss = 174.96
Finished [100%]: Average Loss = 140.14
Finished [100%]: Average Loss = 129.87
Finished [100%]: Average Loss = 124.44
Finished [100%]: Average Loss = 131.62
Finished [100%]: Average Loss = 120.75
Finished [100%]: Average Loss = 137.16
Finished [100%]: Average Loss = 168.88
Finished [100%]: Average Loss = 135.3
Finished [100%]: Average Loss = 164.26
Finished [100%]: Average Loss = 148.59
Finished [100%]: Average Loss = 152.95
Finished [100%]: Average Loss = 157.56
Finished [100%]: Average Loss = 160.91
Finished [100%]: Average Loss = 158.61
Finished [100%]: Average Loss = 158.69
Finished [100%]: Average Loss = 177.04
Finished [100%]: Average Loss = 186.91
Finished [100%]: Average Loss = 144.55
Finished [100%]: Average Loss = 125.96
Finished [100%]: Average Loss = 135.52
Finished [100%]: Average Loss = 144.28
Finished [100%]: Average Loss = 188.71
Finished [100%]: Average Loss = 143.14
Finished [100%]: Average Loss = 153.12
Finished [100%]: Average Loss = 143.66
Finished [100%]: Average Loss = 171.36
Finished [100%]: Average Loss = 178.58
Finished [100%]: Average Loss = 166.51
Finished [100%]: Average Loss = 182.05
Finished [100%]: Average Loss = 161.59
Finished [100%]: Average Loss = 168.07
Finished [100%]: Average Loss = 188.5
Finished [100%]: Average Loss = 158.89
Finished [100%]: Average Loss = 163.83
Finished [100%]: Average Loss = 139.74
Finished [100%]: Average Loss = 175.01
Finished [100%]: Average Loss = 142.01
Finished [100%]: Average Loss = 158.79
Finished [100%]: Average Loss = 161.35
Finished [100%]: Average Loss = 154.23
Finished [100%]: Average Loss = 154.38
Finished [100%]: Average Loss = 150.12
Finished [100%]: Average Loss = 142.43
Finished [100%]: Average Loss = 158.17
Finished [100%]: Average Loss = 158.89
Finished [100%]: Average Loss = 163.01
Finished [100%]: Average Loss = 166.5
Finished [100%]: Average Loss = 169.02
Finished [100%]: Average Loss = 162.82
Finished [100%]: Average Loss = 169.54
Finished [100%]: Average Loss = 176.51
Finished [100%]: Average Loss = 198.32
Finished [100%]: Average Loss = 176.65
Finished [100%]: Average Loss = 157.89
Finished [100%]: Average Loss = 175.61
Finished [100%]: Average Loss = 173.39
Finished [100%]: Average Loss = 184.98
Finished [100%]: Average Loss = 198.98
Finished [100%]: Average Loss = 190.55
Finished [100%]: Average Loss = 231.22
Finished [100%]: Average Loss = 224.26
Finished [100%]: Average Loss = 182.16
Finished [100%]: Average Loss = 156.78
Finished [100%]: Average Loss = 169.5
Finished [100%]: Average Loss = 203.03
Finished [100%]: Average Loss = 183.53
Finished [100%]: Average Loss = 170.84
Finished [100%]: Average Loss = 152.95
Finished [100%]: Average Loss = 147.99
Finished [100%]: Average Loss = 120.38
Finished [100%]: Average Loss = 168.15
Finished [100%]: Average Loss = 163.63
Finished [100%]: Average Loss = 195.39
Finished [100%]: Average Loss = 156.39
Finished [100%]: Average Loss = 178.9
Finished [100%]: Average Loss = 164.34
Finished [100%]: Average Loss = 162
Finished [100%]: Average Loss = 166.56
Finished [100%]: Average Loss = 163.05
Finished [100%]: Average Loss = 164.6
Finished [100%]: Average Loss = 164.78
Finished [100%]: Average Loss = 176.86
Finished [100%]: Average Loss = 180.86
Finished [100%]: Average Loss = 163.44
Finished [100%]: Average Loss = 163.24
Finished [100%]: Average Loss = 163.57
Finished [100%]: Average Loss = 159.28
Finished [100%]: Average Loss = 172.02
Finished [100%]: Average Loss = 149.65
Finished [100%]: Average Loss = 165.13
Finished [100%]: Average Loss = 172.67
Finished [100%]: Average Loss = 156.51
Finished [100%]: Average Loss = 180.13
Finished [100%]: Average Loss = 161.23
Finished [100%]: Average Loss = 157.45
Finished [100%]: Average Loss = 158.23
Finished [100%]: Average Loss = 161.1
Finished [100%]: Average Loss = 164.41
Finished [100%]: Average Loss = 181.78
Finished [100%]: Average Loss = 146.34
Finished [100%]: Average Loss = 180.15
Finished [100%]: Average Loss = 158.95
Finished [100%]: Average Loss = 158.96
Finished [100%]: Average Loss = 162.34
Finished [100%]: Average Loss = 162.24
Finished [100%]: Average Loss = 156.57
Finished [100%]: Average Loss = 154.3
Finished [100%]: Average Loss = 137.66
Finished [100%]: Average Loss = 191.09
Finished [100%]: Average Loss = 166.21
Finished [100%]: Average Loss = 137.45
Finished [100%]: Average Loss = 149.29
Finished [100%]: Average Loss = 165.9
Finished [100%]: Average Loss = 162.88
Finished [100%]: Average Loss = 146.82
Finished [100%]: Average Loss = 168.37
Finished [100%]: Average Loss = 167.03
Finished [100%]: Average Loss = 186.73
Finished [100%]: Average Loss = 160.97
Finished [100%]: Average Loss = 162.96
Finished [100%]: Average Loss = 134.12
Finished [100%]: Average Loss = 148.37
Finished [100%]: Average Loss = 146.39
Finished [100%]: Average Loss = 160.44
Finished [100%]: Average Loss = 183.86
Finished [100%]: Average Loss = 160.25
Finished [100%]: Average Loss = 168.39
Finished [100%]: Average Loss = 159.47
Finished [100%]: Average Loss = 160.39
Finished [100%]: Average Loss = 148.26
Finished [100%]: Average Loss = 170.17
Finished [100%]: Average Loss = 183.45
Finished [100%]: Average Loss = 170.06
Finished [100%]: Average Loss = 150.58
Finished [100%]: Average Loss = 186.18
Finished [100%]: Average Loss = 166.57
Finished [100%]: Average Loss = 167.26
Finished [100%]: Average Loss = 142.37
Finished [100%]: Average Loss = 143.61
Finished [100%]: Average Loss = 166.92
Finished [100%]: Average Loss = 158.29
Finished [100%]: Average Loss = 162.21
Finished [100%]: Average Loss = 166.01
Finished [100%]: Average Loss = 143.62
Finished [100%]: Average Loss = 139.61
Finished [100%]: Average Loss = 137.49
Finished [100%]: Average Loss = 142.22
Finished [100%]: Average Loss = 158.31
Finished [100%]: Average Loss = 168.7
Finished [100%]: Average Loss = 160.55
Finished [100%]: Average Loss = 133.49
Finished [100%]: Average Loss = 147.17
Finished [100%]: Average Loss = 165.09
Finished [100%]: Average Loss = 150.36
Finished [100%]: Average Loss = 186.19
Finished [100%]: Average Loss = 148.53
Finished [100%]: Average Loss = 162.11
Finished [100%]: Average Loss = 162.4
Finished [100%]: Average Loss = 143.54
Finished [100%]: Average Loss = 181.53
Finished [100%]: Average Loss = 158.81
Finished [100%]: Average Loss = 135.71
Finished [100%]: Average Loss = 146.88
Finished [100%]: Average Loss = 149.13
Finished [100%]: Average Loss = 143.95
Finished [100%]: Average Loss = 143.51
Finished [100%]: Average Loss = 128.86
Finished [100%]: Average Loss = 158.61
Finished [100%]: Average Loss = 143.13
Finished [100%]: Average Loss = 164.99
Finished [100%]: Average Loss = 152.47
Finished [100%]: Average Loss = 147.15
Finished [100%]: Average Loss = 145.55
Finished [100%]: Average Loss = 168.21
Finished [100%]: Average Loss = 148.69
Finished [100%]: Average Loss = 142.28
Finished [100%]: Average Loss = 125.59
Finished [100%]: Average Loss = 164.33
Finished [100%]: Average Loss = 148.84
Finished [100%]: Average Loss = 149.81
Finished [100%]: Average Loss = 159.72
Finished [100%]: Average Loss = 147.08
Finished [100%]: Average Loss = 161.23
Finished [100%]: Average Loss = 166.2
Finished [100%]: Average Loss = 146.2
Finished [100%]: Average Loss = 221.22
Finished [100%]: Average Loss = 224.29
Finished [100%]: Average Loss = 234.66
Finished [100%]: Average Loss = 213.34
Finished [100%]: Average Loss = 211.74
Finished [100%]: Average Loss = 187.88
Finished [100%]: Average Loss = 187.59
Finished [100%]: Average Loss = 154.58
Finished [100%]: Average Loss = 161.73
Finished [100%]: Average Loss = 165.28
Finished [100%]: Average Loss = 198.59
Finished [100%]: Average Loss = 161.84
Finished [100%]: Average Loss = 218.93
Finished [100%]: Average Loss = 162.07
Finished [100%]: Average Loss = 162.51
Finished [100%]: Average Loss = 155.9
Finished [100%]: Average Loss = 176.38
Finished [100%]: Average Loss = 161.6
Finished [100%]: Average Loss = 184.41
Finished [100%]: Average Loss = 183.03
Finished [100%]: Average Loss = 194.14
Finished [100%]: Average Loss = 181.98
Finished [100%]: Average Loss = 161.04
Finished [100%]: Average Loss = 161.2
Finished [100%]: Average Loss = 156.05
Finished [100%]: Average Loss = 196.34
Finished [100%]: Average Loss = 153.73
Finished [100%]: Average Loss = 166.53
Finished [100%]: Average Loss = 161.72
Finished [100%]: Average Loss = 184.91
Finished [100%]: Average Loss = 184.37
Finished [100%]: Average Loss = 162.31
Finished [100%]: Average Loss = 158.87
Finished [100%]: Average Loss = 164.7
Finished [100%]: Average Loss = 180.74
Finished [100%]: Average Loss = 161.66
Finished [100%]: Average Loss = 151.53
Finished [100%]: Average Loss = 157.15
Finished [100%]: Average Loss = 179.18
Finished [100%]: Average Loss = 180.18
Finished [100%]: Average Loss = 164
Finished [100%]: Average Loss = 165.35
Finished [100%]: Average Loss = 167.13
Finished [100%]: Average Loss = 165.39
Finished [100%]: Average Loss = 160.64
Finished [100%]: Average Loss = 180
Finished [100%]: Average Loss = 158.67
Finished [100%]: Average Loss = 158.84
Finished [100%]: Average Loss = 157.93
Finished [100%]: Average Loss = 156.57
Finished [100%]: Average Loss = 171.1
Finished [100%]: Average Loss = 176.43
Finished [100%]: Average Loss = 172.51
Finished [100%]: Average Loss = 172.15
Finished [100%]: Average Loss = 170.56
Finished [100%]: Average Loss = 169.93
Finished [100%]: Average Loss = 169.41
Finished [100%]: Average Loss = 167.37
Finished [100%]: Average Loss = 164.62
Finished [100%]: Average Loss = 166.57
Finished [100%]: Average Loss = 141.33
Finished [100%]: Average Loss = 160.19
Finished [100%]: Average Loss = 176.64
Finished [100%]: Average Loss = 173.75
Finished [100%]: Average Loss = 155.06
Finished [100%]: Average Loss = 159.92
Finished [100%]: Average Loss = 157.54
Finished [100%]: Average Loss = 132.5
Finished [100%]: Average Loss = 133.1
Finished [100%]: Average Loss = 148.05
Finished [100%]: Average Loss = 156.07
Finished [100%]: Average Loss = 168.18
Finished [100%]: Average Loss = 145.94
Finished [100%]: Average Loss = 146.47
Finished [100%]: Average Loss = 165.49
Finished [100%]: Average Loss = 175.01
Finished [100%]: Average Loss = 185.05
Finished [100%]: Average Loss = 159.09
Finished [100%]: Average Loss = 154.38
Finished [100%]: Average Loss = 146.47
Finished [100%]: Average Loss = 137.15
Finished [100%]: Average Loss = 154.97
Finished [100%]: Average Loss = 165.92
Finished [100%]: Average Loss = 169.09
Finished [100%]: Average Loss = 172.64
Finished [100%]: Average Loss = 174.63
Finished [100%]: Average Loss = 127.51
Finished [100%]: Average Loss = 171.17
Finished [100%]: Average Loss = 181.31
Finished [100%]: Average Loss = 158.52

Total time: 1020.5 seconds
Weeks fit: 391
Weeks skipped: 0

In [ ]:
weeklyMetricsMEDF = pd.DataFrame(weeklyMetricsME)
print(weeklyMetricsMEDF[['week', 'entropy']].describe())

          entropy
count  391.000000
mean     3.778652
std      1.011246
min      0.800093
25%      3.092180
50%      3.823763
75%      4.543043
max      5.927773

In [ ]:
longRowsME = []

for _, row in weeklyMetricsMEDF.iterrows():
    week = row['week']
    region = row['region']
    entropy = row['entropy']

    flipProbs = parseMetricDict(row['flipProbabilities'])
    hdiOverlaps = parseMetricDict(row['hdiOverlaps'])

    for pairLabel, flipProb in flipProbs.items():
        countryI, countryJ = pairLabel.split(' over ')
        overlap = hdiOverlaps.get(f"{countryI} vs {countryJ}", None)

        longRowsME.append({
            'week': week,
            'region': region,
            'entropy': entropy,
            'countryI': countryI,
            'countryJ': countryJ,
            'flipProbability': flipProb,
            'hdiOverlap': overlap
        })

longFormMEDF = pd.DataFrame(longRowsME)
print(longFormMEDF.shape)
longFormMEDF.head()

(30498, 7)

,week,region,entropy,countryI,countryJ,flipProbability,hdiOverlap
0,2018-01-01/2018-01-07,Middle East,4.774322,Bahrain,Iran,0.0000,False
1,2018-01-01/2018-01-07,Middle East,4.774322,Bahrain,Iraq,0.9725,True
2,2018-01-01/2018-01-07,Middle East,4.774322,Bahrain,Israel,1.0000,False
3,2018-01-01/2018-01-07,Middle East,4.774322,Bahrain,Jordan,1.0000,False
4,2018-01-01/2018-01-07,Middle East,4.774322,Bahrain,Kuwait,0.1900,True

In [ ]:
longFormMEDF.to_csv('../Data/Processed/weeklyUncertaintyMiddleEast.csv', index=False)

In [ ]:
northAfricaData = countryComparisons[countryComparisons['region'] == 'Northern Africa']

northAfricaCountries = sorted(set(northAfricaData['countryI']) | set(northAfricaData['countryJ']))
northAfricaIndexMap = {country: i for i, country in enumerate(northAfricaCountries)}
nNorthAfricaCountries = len(northAfricaCountries)

northAfricaWeeks = sorted(northAfricaData['week'].unique())

print(nNorthAfricaCountries)
print(len(northAfricaWeeks))

6
391

In [ ]:
initialWeekData = northAfricaData[northAfricaData['week'] == northAfricaWeeks[0]]

initialIndexI = initialWeekData['countryI'].map(northAfricaIndexMap).to_numpy()
initialIndexJ = initialWeekData['countryJ'].map(northAfricaIndexMap).to_numpy()
initialWinsI = initialWeekData['winsI'].to_numpy()
initialTotals  = initialWeekData['total'].to_numpy()

with pm.Model() as rollingModelNA:
    indexIData = pm.Data('indexIData', initialIndexI)
    indexJData = pm.Data('indexJData', initialIndexJ)
    winsIData = pm.Data('winsIData', initialWinsI)
    totalsData = pm.Data('totalsData', initialTotals)

    beta = pm.ZeroSumNormal('beta', sigma=1.0, shape=nNorthAfricaCountries)
    p = pm.math.sigmoid(beta[indexIData] - beta[indexJData])
    obs = pm.Binomial('obs', n=totalsData, p=p, observed=winsIData)

In [ ]:
weeklyMetricsNA = []
weeksSkippedNA = []

startTime = time.time() 

for week in northAfricaWeeks: 
    weekData = northAfricaData[northAfricaData['week'] == week]

    if len(weekData) == 0: 
        weeksSkippedNA.append(week)
        continue

    indexI = weekData['countryI'].map(northAfricaIndexMap).to_numpy()
    indexJ = weekData['countryJ'].map(northAfricaIndexMap).to_numpy()
    winsI = weekData['winsI'].to_numpy()
    totals = weekData['total'].to_numpy()

    with rollingModelNA: 
        pm.set_data({
            'indexIData' : indexI, 
            'indexJData' : indexJ, 
            'winsIData' : winsI, 
            'totalsData' : totals
        })

        approx = pm.fit(n=20000, method='advi', progressbar=False)
        trace = approx.sample(400)

    results = computeUncertainty(trace, northAfricaCountries)

    weeklyMetricsNA.append({
        'week': week,
        'region': 'Northern Africa',
        'entropy': results['entropy'],
        'flipProbabilities': results['flipProbabilities'],
        'hdiOverlaps': results['hdiOverlaps']
    })

endTime = time.time()

print(f"Total time: {endTime - startTime:.1f} seconds")
print(f"Weeks fit: {len(weeklyMetricsNA)}")
print(f"Weeks skipped: {len(weeksSkippedNA)}")

Finished [100%]: Average Loss = 32.269
Finished [100%]: Average Loss = 44.187
Finished [100%]: Average Loss = 38.215
Finished [100%]: Average Loss = 34.988
Finished [100%]: Average Loss = 35.894
Finished [100%]: Average Loss = 31.552
Finished [100%]: Average Loss = 34.709
Finished [100%]: Average Loss = 33.673
Finished [100%]: Average Loss = 32.439
Finished [100%]: Average Loss = 34.466
Finished [100%]: Average Loss = 33.092
Finished [100%]: Average Loss = 32.531
Finished [100%]: Average Loss = 23.198
Finished [100%]: Average Loss = 16.658
Finished [100%]: Average Loss = 29.653
Finished [100%]: Average Loss = 30.99
Finished [100%]: Average Loss = 32.309
Finished [100%]: Average Loss = 28.303
Finished [100%]: Average Loss = 29.213
Finished [100%]: Average Loss = 32.329
Finished [100%]: Average Loss = 34.112
Finished [100%]: Average Loss = 25.902
Finished [100%]: Average Loss = 31.787
Finished [100%]: Average Loss = 23.565
Finished [100%]: Average Loss = 28.875
Finished [100%]: Average Loss = 31.887
Finished [100%]: Average Loss = 27.53
Finished [100%]: Average Loss = 30.86
Finished [100%]: Average Loss = 21.786
Finished [100%]: Average Loss = 30.641
Finished [100%]: Average Loss = 22.674
Finished [100%]: Average Loss = 18.15
Finished [100%]: Average Loss = 29.297
Finished [100%]: Average Loss = 24.733
Finished [100%]: Average Loss = 33.771
Finished [100%]: Average Loss = 35.165
Finished [100%]: Average Loss = 20.09
Finished [100%]: Average Loss = 24.598
Finished [100%]: Average Loss = 32.391
Finished [100%]: Average Loss = 22.099
Finished [100%]: Average Loss = 30.555
Finished [100%]: Average Loss = 32.66
Finished [100%]: Average Loss = 36.401
Finished [100%]: Average Loss = 25.24
Finished [100%]: Average Loss = 37.593
Finished [100%]: Average Loss = 40.522
Finished [100%]: Average Loss = 38.671
Finished [100%]: Average Loss = 40.875
Finished [100%]: Average Loss = 43.342
Finished [100%]: Average Loss = 42.171
Finished [100%]: Average Loss = 43.347
Finished [100%]: Average Loss = 43.099
Finished [100%]: Average Loss = 41.149
Finished [100%]: Average Loss = 41.31
Finished [100%]: Average Loss = 44.596
Finished [100%]: Average Loss = 42.777
Finished [100%]: Average Loss = 39.232
Finished [100%]: Average Loss = 41.316
Finished [100%]: Average Loss = 39.852
Finished [100%]: Average Loss = 45.33
Finished [100%]: Average Loss = 45.303
Finished [100%]: Average Loss = 44.462
Finished [100%]: Average Loss = 44.101
Finished [100%]: Average Loss = 43.49
Finished [100%]: Average Loss = 43.665
Finished [100%]: Average Loss = 43.045
Finished [100%]: Average Loss = 46.056
Finished [100%]: Average Loss = 44.128
Finished [100%]: Average Loss = 47.33
Finished [100%]: Average Loss = 44.328
Finished [100%]: Average Loss = 41.452
Finished [100%]: Average Loss = 42.58
Finished [100%]: Average Loss = 43.781
Finished [100%]: Average Loss = 43.022
Finished [100%]: Average Loss = 39.637
Finished [100%]: Average Loss = 40.886
Finished [100%]: Average Loss = 41.617
Finished [100%]: Average Loss = 39.845
Finished [100%]: Average Loss = 41.701
Finished [100%]: Average Loss = 42.64
Finished [100%]: Average Loss = 43.761
Finished [100%]: Average Loss = 42.516
Finished [100%]: Average Loss = 39.512
Finished [100%]: Average Loss = 39.48
Finished [100%]: Average Loss = 39.19
Finished [100%]: Average Loss = 41.788
Finished [100%]: Average Loss = 42.879
Finished [100%]: Average Loss = 40.854
Finished [100%]: Average Loss = 41.678
Finished [100%]: Average Loss = 43.756
Finished [100%]: Average Loss = 45.847
Finished [100%]: Average Loss = 42.429
Finished [100%]: Average Loss = 38.333
Finished [100%]: Average Loss = 41.967
Finished [100%]: Average Loss = 44.631
Finished [100%]: Average Loss = 42.88
Finished [100%]: Average Loss = 40.99
Finished [100%]: Average Loss = 44.018
Finished [100%]: Average Loss = 40.642
Finished [100%]: Average Loss = 43.791
Finished [100%]: Average Loss = 42.829
Finished [100%]: Average Loss = 44.345
Finished [100%]: Average Loss = 42.137
Finished [100%]: Average Loss = 38.969
Finished [100%]: Average Loss = 41.406
Finished [100%]: Average Loss = 39.8
Finished [100%]: Average Loss = 40.508
Finished [100%]: Average Loss = 40.194
Finished [100%]: Average Loss = 44.733
Finished [100%]: Average Loss = 43.326
Finished [100%]: Average Loss = 44.546
Finished [100%]: Average Loss = 43.544
Finished [100%]: Average Loss = 44.256
Finished [100%]: Average Loss = 45.454
Finished [100%]: Average Loss = 43.348
Finished [100%]: Average Loss = 37.895
Finished [100%]: Average Loss = 37.482
Finished [100%]: Average Loss = 36.597
Finished [100%]: Average Loss = 36.326
Finished [100%]: Average Loss = 40.711
Finished [100%]: Average Loss = 40.888
Finished [100%]: Average Loss = 39.507
Finished [100%]: Average Loss = 42.427
Finished [100%]: Average Loss = 43.938
Finished [100%]: Average Loss = 42.703
Finished [100%]: Average Loss = 42.754
Finished [100%]: Average Loss = 44.293
Finished [100%]: Average Loss = 43.374
Finished [100%]: Average Loss = 41.909
Finished [100%]: Average Loss = 41.687
Finished [100%]: Average Loss = 41.768
Finished [100%]: Average Loss = 44.611
Finished [100%]: Average Loss = 41.479
Finished [100%]: Average Loss = 42.764
Finished [100%]: Average Loss = 40.022
Finished [100%]: Average Loss = 40.589
Finished [100%]: Average Loss = 40.526
Finished [100%]: Average Loss = 44.225
Finished [100%]: Average Loss = 44.912
Finished [100%]: Average Loss = 39.642
Finished [100%]: Average Loss = 42.533
Finished [100%]: Average Loss = 39.885
Finished [100%]: Average Loss = 47.161
Finished [100%]: Average Loss = 42.056
Finished [100%]: Average Loss = 45.127
Finished [100%]: Average Loss = 42.104
Finished [100%]: Average Loss = 43.461
Finished [100%]: Average Loss = 40.955
Finished [100%]: Average Loss = 41.25
Finished [100%]: Average Loss = 41.281
Finished [100%]: Average Loss = 29.587
Finished [100%]: Average Loss = 40.603
Finished [100%]: Average Loss = 41.556
Finished [100%]: Average Loss = 43.671
Finished [100%]: Average Loss = 42.936
Finished [100%]: Average Loss = 38.71
Finished [100%]: Average Loss = 40.174
Finished [100%]: Average Loss = 39.147
Finished [100%]: Average Loss = 32.165
Finished [100%]: Average Loss = 44.926
Finished [100%]: Average Loss = 41.862
Finished [100%]: Average Loss = 41.805
Finished [100%]: Average Loss = 32.695
Finished [100%]: Average Loss = 38.511
Finished [100%]: Average Loss = 41.099
Finished [100%]: Average Loss = 31.184
Finished [100%]: Average Loss = 28.849
Finished [100%]: Average Loss = 39.846
Finished [100%]: Average Loss = 41.685
Finished [100%]: Average Loss = 38.272
Finished [100%]: Average Loss = 45.024
Finished [100%]: Average Loss = 38.261
Finished [100%]: Average Loss = 38.006
Finished [100%]: Average Loss = 31.807
Finished [100%]: Average Loss = 29.851
Finished [100%]: Average Loss = 40.275
Finished [100%]: Average Loss = 43.633
Finished [100%]: Average Loss = 38.93
Finished [100%]: Average Loss = 37.436
Finished [100%]: Average Loss = 39.56
Finished [100%]: Average Loss = 41.045
Finished [100%]: Average Loss = 36.501
Finished [100%]: Average Loss = 37.798
Finished [100%]: Average Loss = 38.722
Finished [100%]: Average Loss = 40.989
Finished [100%]: Average Loss = 32.905
Finished [100%]: Average Loss = 40.236
Finished [100%]: Average Loss = 39.098
Finished [100%]: Average Loss = 35.755
Finished [100%]: Average Loss = 34.522
Finished [100%]: Average Loss = 37.02
Finished [100%]: Average Loss = 36.737
Finished [100%]: Average Loss = 38.748
Finished [100%]: Average Loss = 39.396
Finished [100%]: Average Loss = 36.539
Finished [100%]: Average Loss = 36.517
Finished [100%]: Average Loss = 37.94
Finished [100%]: Average Loss = 37.155
Finished [100%]: Average Loss = 29.691
Finished [100%]: Average Loss = 38.916
Finished [100%]: Average Loss = 40.048
Finished [100%]: Average Loss = 37.761
Finished [100%]: Average Loss = 40.347
Finished [100%]: Average Loss = 42.844
Finished [100%]: Average Loss = 41.595
Finished [100%]: Average Loss = 39.162
Finished [100%]: Average Loss = 41.266
Finished [100%]: Average Loss = 39.408
Finished [100%]: Average Loss = 40.636
Finished [100%]: Average Loss = 39.519
Finished [100%]: Average Loss = 38.772
Finished [100%]: Average Loss = 37.885
Finished [100%]: Average Loss = 39.061
Finished [100%]: Average Loss = 35.57
Finished [100%]: Average Loss = 37.202
Finished [100%]: Average Loss = 40.074
Finished [100%]: Average Loss = 41.316
Finished [100%]: Average Loss = 40.545
Finished [100%]: Average Loss = 40.692
Finished [100%]: Average Loss = 38.544
Finished [100%]: Average Loss = 40.245
Finished [100%]: Average Loss = 39.858
Finished [100%]: Average Loss = 37.967
Finished [100%]: Average Loss = 26.904
Finished [100%]: Average Loss = 40.345
Finished [100%]: Average Loss = 36.433
Finished [100%]: Average Loss = 25.764
Finished [100%]: Average Loss = 38.732
Finished [100%]: Average Loss = 29.118
Finished [100%]: Average Loss = 34.45
Finished [100%]: Average Loss = 37.506
Finished [100%]: Average Loss = 37.459
Finished [100%]: Average Loss = 35.04
Finished [100%]: Average Loss = 38.055
Finished [100%]: Average Loss = 40.493
Finished [100%]: Average Loss = 37.249
Finished [100%]: Average Loss = 29.834
Finished [100%]: Average Loss = 33.928
Finished [100%]: Average Loss = 33.447
Finished [100%]: Average Loss = 33.484
Finished [100%]: Average Loss = 36.073
Finished [100%]: Average Loss = 33.517
Finished [100%]: Average Loss = 32.868
Finished [100%]: Average Loss = 33.696
Finished [100%]: Average Loss = 35.984
Finished [100%]: Average Loss = 34.077
Finished [100%]: Average Loss = 38.219
Finished [100%]: Average Loss = 35.91
Finished [100%]: Average Loss = 34.788
Finished [100%]: Average Loss = 36.568
Finished [100%]: Average Loss = 30.128
Finished [100%]: Average Loss = 35.626
Finished [100%]: Average Loss = 36.697
Finished [100%]: Average Loss = 38.795
Finished [100%]: Average Loss = 36.167
Finished [100%]: Average Loss = 32.951
Finished [100%]: Average Loss = 26.768
Finished [100%]: Average Loss = 34.689
Finished [100%]: Average Loss = 26.567
Finished [100%]: Average Loss = 31.339
Finished [100%]: Average Loss = 38.129
Finished [100%]: Average Loss = 34.564
Finished [100%]: Average Loss = 27.712
Finished [100%]: Average Loss = 27.554
Finished [100%]: Average Loss = 26.782
Finished [100%]: Average Loss = 36.748
Finished [100%]: Average Loss = 36.862
Finished [100%]: Average Loss = 28.02
Finished [100%]: Average Loss = 30.273
Finished [100%]: Average Loss = 37.502
Finished [100%]: Average Loss = 35.241
Finished [100%]: Average Loss = 25.257
Finished [100%]: Average Loss = 30.726
Finished [100%]: Average Loss = 35.04
Finished [100%]: Average Loss = 25.052
Finished [100%]: Average Loss = 31.151
Finished [100%]: Average Loss = 20.059
Finished [100%]: Average Loss = 28.948
Finished [100%]: Average Loss = 31.158
Finished [100%]: Average Loss = 37.149
Finished [100%]: Average Loss = 30.923
Finished [100%]: Average Loss = 37.361
Finished [100%]: Average Loss = 29.07
Finished [100%]: Average Loss = 27.07
Finished [100%]: Average Loss = 33.344
Finished [100%]: Average Loss = 36.699
Finished [100%]: Average Loss = 23.842
Finished [100%]: Average Loss = 35.498
Finished [100%]: Average Loss = 37.546
Finished [100%]: Average Loss = 29.235
Finished [100%]: Average Loss = 39.708
Finished [100%]: Average Loss = 39.246
Finished [100%]: Average Loss = 37.605
Finished [100%]: Average Loss = 29.938
Finished [100%]: Average Loss = 39.831
Finished [100%]: Average Loss = 40.45
Finished [100%]: Average Loss = 30.214
Finished [100%]: Average Loss = 19.704
Finished [100%]: Average Loss = 35.231
Finished [100%]: Average Loss = 28.36
Finished [100%]: Average Loss = 40.38
Finished [100%]: Average Loss = 47.261
Finished [100%]: Average Loss = 54.178
Finished [100%]: Average Loss = 45.632
Finished [100%]: Average Loss = 41.385
Finished [100%]: Average Loss = 40.679
Finished [100%]: Average Loss = 41.285
Finished [100%]: Average Loss = 41.125
Finished [100%]: Average Loss = 31.464
Finished [100%]: Average Loss = 32
Finished [100%]: Average Loss = 39.849
Finished [100%]: Average Loss = 39.137
Finished [100%]: Average Loss = 39.67
Finished [100%]: Average Loss = 32.3
Finished [100%]: Average Loss = 42.464
Finished [100%]: Average Loss = 43.044
Finished [100%]: Average Loss = 22.273
Finished [100%]: Average Loss = 42.641
Finished [100%]: Average Loss = 41.267
Finished [100%]: Average Loss = 32.871
Finished [100%]: Average Loss = 42.162
Finished [100%]: Average Loss = 41.813
Finished [100%]: Average Loss = 42.582
Finished [100%]: Average Loss = 39.795
Finished [100%]: Average Loss = 39.42
Finished [100%]: Average Loss = 35.51
Finished [100%]: Average Loss = 44.671
Finished [100%]: Average Loss = 38.476
Finished [100%]: Average Loss = 41.682
Finished [100%]: Average Loss = 42.98
Finished [100%]: Average Loss = 42.076
Finished [100%]: Average Loss = 40.944
Finished [100%]: Average Loss = 42.672
Finished [100%]: Average Loss = 39.338
Finished [100%]: Average Loss = 41.248
Finished [100%]: Average Loss = 41.679
Finished [100%]: Average Loss = 40.477
Finished [100%]: Average Loss = 37.364
Finished [100%]: Average Loss = 39.181
Finished [100%]: Average Loss = 38.992
Finished [100%]: Average Loss = 30.178
Finished [100%]: Average Loss = 40.143
Finished [100%]: Average Loss = 39.783
Finished [100%]: Average Loss = 29.89
Finished [100%]: Average Loss = 40.523
Finished [100%]: Average Loss = 31.758
Finished [100%]: Average Loss = 39.375
Finished [100%]: Average Loss = 31.169
Finished [100%]: Average Loss = 42.301
Finished [100%]: Average Loss = 40.361
Finished [100%]: Average Loss = 39.243
Finished [100%]: Average Loss = 41.557
Finished [100%]: Average Loss = 41.444
Finished [100%]: Average Loss = 41.658
Finished [100%]: Average Loss = 41.933
Finished [100%]: Average Loss = 43.598
Finished [100%]: Average Loss = 39.382
Finished [100%]: Average Loss = 41.313
Finished [100%]: Average Loss = 31.529
Finished [100%]: Average Loss = 41.167
Finished [100%]: Average Loss = 32.063
Finished [100%]: Average Loss = 39.584
Finished [100%]: Average Loss = 37.4
Finished [100%]: Average Loss = 21.613
Finished [100%]: Average Loss = 39.133
Finished [100%]: Average Loss = 39.184
Finished [100%]: Average Loss = 42.498
Finished [100%]: Average Loss = 42.739
Finished [100%]: Average Loss = 43.816
Finished [100%]: Average Loss = 39.031
Finished [100%]: Average Loss = 37.743
Finished [100%]: Average Loss = 42.797
Finished [100%]: Average Loss = 41.932
Finished [100%]: Average Loss = 38.224
Finished [100%]: Average Loss = 35.614
Finished [100%]: Average Loss = 28.941
Finished [100%]: Average Loss = 41.919
Finished [100%]: Average Loss = 40.015
Finished [100%]: Average Loss = 43.898
Finished [100%]: Average Loss = 45.719
Finished [100%]: Average Loss = 41.855
Finished [100%]: Average Loss = 32.252
Finished [100%]: Average Loss = 42.818
Finished [100%]: Average Loss = 39.999
Finished [100%]: Average Loss = 45.044
Finished [100%]: Average Loss = 41.523
Finished [100%]: Average Loss = 42.042
Finished [100%]: Average Loss = 28.94
Finished [100%]: Average Loss = 39.704
Finished [100%]: Average Loss = 42.167
Finished [100%]: Average Loss = 25.401

Total time: 771.3 seconds
Weeks fit: 391
Weeks skipped: 0

In [ ]:
weeklyMetricsNADF = pd.DataFrame(weeklyMetricsNA)
print(weeklyMetricsNADF[['week', 'entropy']].describe())

          entropy
count  391.000000
mean     1.631581
std      0.833683
min      0.139355
25%      1.032420
50%      1.494632
75%      2.097244
max      5.164969

In [ ]:
longRowsNA = []

for _, row in weeklyMetricsNADF.iterrows():
    week = row['week']
    region = row['region']
    entropy = row['entropy']

    flipProbs = parseMetricDict(row['flipProbabilities'])
    hdiOverlaps = parseMetricDict(row['hdiOverlaps'])

    for pairLabel, flipProb in flipProbs.items():
        countryI, countryJ = pairLabel.split(' over ')
        overlap = hdiOverlaps.get(f"{countryI} vs {countryJ}", None)

        longRowsNA.append({
            'week': week,
            'region': region,
            'entropy': entropy,
            'countryI': countryI,
            'countryJ': countryJ,
            'flipProbability': flipProb,
            'hdiOverlap': overlap
        })

longFormNADF = pd.DataFrame(longRowsNA)
print(longFormNADF.shape)

(5865, 7)

In [ ]:
longFormNADF.to_csv('../Data/Processed/weeklyUncertaintyNorthAfrica.csv', index=False)

In [6]:
europeData = countryComparisons[countryComparisons['region'] == 'Europe']

europeCountries = sorted(set(europeData['countryI']) | set(europeData['countryJ']))
europeIndexMap = {country: i for i, country in enumerate(europeCountries)}
nEuropeCountries = len(europeCountries)

europeWeeks = sorted(europeData['week'].unique())

print(nEuropeCountries)
print(len(europeWeeks))

41
391

In [10]:
initialWeekData = europeData[europeData['week'] == europeWeeks[0]]

initialIndexI = initialWeekData['countryI'].map(europeIndexMap).to_numpy()
initialIndexJ = initialWeekData['countryJ'].map(europeIndexMap).to_numpy()
initialWinsI = initialWeekData['winsI'].to_numpy()
initialTotals  = initialWeekData['total'].to_numpy()

with pm.Model() as rollingModelEurope:
    indexIData = pm.Data('indexIData', initialIndexI)
    indexJData = pm.Data('indexJData', initialIndexJ)
    winsIData = pm.Data('winsIData', initialWinsI)
    totalsData = pm.Data('totalsData', initialTotals)

    beta = pm.ZeroSumNormal('beta', sigma=1.0, shape=nEuropeCountries)
    p = pm.math.sigmoid(beta[indexIData] - beta[indexJData])
    obs = pm.Binomial('obs', n=totalsData, p=p, observed=winsIData)

In [11]:
import time

weeklyMetricsEurope = []
weeksSkippedEurope = []

startTime = time.time()

for week in europeWeeks:
    weekData = europeData[europeData['week'] == week]

    if len(weekData) == 0:
        weeksSkippedEurope.append(week)
        continue

    indexI = weekData['countryI'].map(europeIndexMap).to_numpy()
    indexJ = weekData['countryJ'].map(europeIndexMap).to_numpy()
    winsI = weekData['winsI'].to_numpy()
    totals = weekData['total'].to_numpy()

    with rollingModelEurope:
        pm.set_data({
            'indexIData': indexI,
            'indexJData': indexJ,
            'winsIData': winsI,
            'totalsData': totals
        })

        approx = pm.fit(n=20000, method='advi', progressbar=False)
        trace = approx.sample(400)

    results = computeUncertainty(trace, europeCountries)

    weeklyMetricsEurope.append({
        'week': week,
        'region': 'Europe',
        'entropy': results['entropy'],
        'flipProbabilities': results['flipProbabilities'],
        'hdiOverlaps': results['hdiOverlaps']
    })

endTime = time.time()

print(f"Total time: {endTime - startTime:.1f} seconds")
print(f"Weeks fit: {len(weeklyMetricsEurope)}")
print(f"Weeks skipped: {len(weeksSkippedEurope)}")

Finished [100%]: Average Loss = 48.034
Finished [100%]: Average Loss = 100.1
Finished [100%]: Average Loss = 144.49
Finished [100%]: Average Loss = 134.44
Finished [100%]: Average Loss = 163.07
Finished [100%]: Average Loss = 151.21
Finished [100%]: Average Loss = 156.72
Finished [100%]: Average Loss = 164.45
Finished [100%]: Average Loss = 179.03
Finished [100%]: Average Loss = 177.02
Finished [100%]: Average Loss = 145.39
Finished [100%]: Average Loss = 138.01
Finished [100%]: Average Loss = 142.12
Finished [100%]: Average Loss = 168.66
Finished [100%]: Average Loss = 104.91
Finished [100%]: Average Loss = 154.81
Finished [100%]: Average Loss = 159.61
Finished [100%]: Average Loss = 147.57
Finished [100%]: Average Loss = 137.78
Finished [100%]: Average Loss = 158.6
Finished [100%]: Average Loss = 159.2
Finished [100%]: Average Loss = 131.94
Finished [100%]: Average Loss = 199.94
Finished [100%]: Average Loss = 198.29
Finished [100%]: Average Loss = 196.06
Finished [100%]: Average Loss = 165.26
Finished [100%]: Average Loss = 165.49
Finished [100%]: Average Loss = 147.96
Finished [100%]: Average Loss = 146.65
Finished [100%]: Average Loss = 150.27
Finished [100%]: Average Loss = 82.48
Finished [100%]: Average Loss = 94.868
Finished [100%]: Average Loss = 127.86
Finished [100%]: Average Loss = 121.96
Finished [100%]: Average Loss = 145.31
Finished [100%]: Average Loss = 181.41
Finished [100%]: Average Loss = 163.8
Finished [100%]: Average Loss = 170.78
Finished [100%]: Average Loss = 172.51
Finished [100%]: Average Loss = 192.71
Finished [100%]: Average Loss = 139.64
Finished [100%]: Average Loss = 158.18
Finished [100%]: Average Loss = 154.8
Finished [100%]: Average Loss = 187.26
Finished [100%]: Average Loss = 165.02
Finished [100%]: Average Loss = 187.12
Finished [100%]: Average Loss = 166.01
Finished [100%]: Average Loss = 186.49
Finished [100%]: Average Loss = 187.11
Finished [100%]: Average Loss = 179.81
Finished [100%]: Average Loss = 181.25
Finished [100%]: Average Loss = 166.12
Finished [100%]: Average Loss = 83.936
Finished [100%]: Average Loss = 140.23
Finished [100%]: Average Loss = 178.16
Finished [100%]: Average Loss = 160.13
Finished [100%]: Average Loss = 180.81
Finished [100%]: Average Loss = 172.66
Finished [100%]: Average Loss = 208.08
Finished [100%]: Average Loss = 178.67
Finished [100%]: Average Loss = 186.99
Finished [100%]: Average Loss = 216.68
Finished [100%]: Average Loss = 211.38
Finished [100%]: Average Loss = 210.25
Finished [100%]: Average Loss = 208.91
Finished [100%]: Average Loss = 202.67
Finished [100%]: Average Loss = 208.1
Finished [100%]: Average Loss = 183.47
Finished [100%]: Average Loss = 202.53
Finished [100%]: Average Loss = 188.93
Finished [100%]: Average Loss = 191.71
Finished [100%]: Average Loss = 174.95
Finished [100%]: Average Loss = 194.54
Finished [100%]: Average Loss = 182.78
Finished [100%]: Average Loss = 197.93
Finished [100%]: Average Loss = 149.37
Finished [100%]: Average Loss = 188.93
Finished [100%]: Average Loss = 183.96
Finished [100%]: Average Loss = 202.15
Finished [100%]: Average Loss = 196.07
Finished [100%]: Average Loss = 188.9
Finished [100%]: Average Loss = 183.72
Finished [100%]: Average Loss = 176.72
Finished [100%]: Average Loss = 121.48
Finished [100%]: Average Loss = 174.49
Finished [100%]: Average Loss = 154.51
Finished [100%]: Average Loss = 180.67
Finished [100%]: Average Loss = 162.05
Finished [100%]: Average Loss = 161.34
Finished [100%]: Average Loss = 208.43
Finished [100%]: Average Loss = 180.04
Finished [100%]: Average Loss = 198.87
Finished [100%]: Average Loss = 198.32
Finished [100%]: Average Loss = 193.9
Finished [100%]: Average Loss = 202.62
Finished [100%]: Average Loss = 193.25
Finished [100%]: Average Loss = 209.64
Finished [100%]: Average Loss = 201.78
Finished [100%]: Average Loss = 175.99
Finished [100%]: Average Loss = 180.66
Finished [100%]: Average Loss = 158.49
Finished [100%]: Average Loss = 187.96
Finished [100%]: Average Loss = 210.28
Finished [100%]: Average Loss = 173.75
Finished [100%]: Average Loss = 500.85
Finished [100%]: Average Loss = 899.75
Finished [100%]: Average Loss = 1,251.1
Finished [100%]: Average Loss = 1,044.9
Finished [100%]: Average Loss = 1,317.7
Finished [100%]: Average Loss = 1,167.7
Finished [100%]: Average Loss = 1,036.2
Finished [100%]: Average Loss = 1,249.7
Finished [100%]: Average Loss = 1,169.4
Finished [100%]: Average Loss = 921.69
Finished [100%]: Average Loss = 1,358.6
Finished [100%]: Average Loss = 605.56
Finished [100%]: Average Loss = 448.13
Finished [100%]: Average Loss = 361.09
Finished [100%]: Average Loss = 328.2
Finished [100%]: Average Loss = 651.57
Finished [100%]: Average Loss = 595.92
Finished [100%]: Average Loss = 970.25
Finished [100%]: Average Loss = 869.23
Finished [100%]: Average Loss = 1,024.5
Finished [100%]: Average Loss = 1,072.6
Finished [100%]: Average Loss = 1,164.2
Finished [100%]: Average Loss = 1,147.7
Finished [100%]: Average Loss = 1,326.9
Finished [100%]: Average Loss = 1,329.8
Finished [100%]: Average Loss = 1,208.1
Finished [100%]: Average Loss = 1,193.6
Finished [100%]: Average Loss = 1,156
Finished [100%]: Average Loss = 1,014.9
Finished [100%]: Average Loss = 1,148.6
Finished [100%]: Average Loss = 1,010.1
Finished [100%]: Average Loss = 912.63
Finished [100%]: Average Loss = 1,205.6
Finished [100%]: Average Loss = 1,027.6
Finished [100%]: Average Loss = 980.77
Finished [100%]: Average Loss = 1,212.8
Finished [100%]: Average Loss = 1,214.4
Finished [100%]: Average Loss = 1,333.3
Finished [100%]: Average Loss = 1,415.7
Finished [100%]: Average Loss = 1,283.6
Finished [100%]: Average Loss = 1,408.4
Finished [100%]: Average Loss = 1,241.5
Finished [100%]: Average Loss = 1,200.4
Finished [100%]: Average Loss = 1,270.4
Finished [100%]: Average Loss = 1,201.1
Finished [100%]: Average Loss = 1,061.6
Finished [100%]: Average Loss = 1,118.3
Finished [100%]: Average Loss = 971.76
Finished [100%]: Average Loss = 1,183.2
Finished [100%]: Average Loss = 1,114.8
Finished [100%]: Average Loss = 1,117.1
Finished [100%]: Average Loss = 894.35
Finished [100%]: Average Loss = 731.6
Finished [100%]: Average Loss = 780.54
Finished [100%]: Average Loss = 935.62
Finished [100%]: Average Loss = 995
Finished [100%]: Average Loss = 1,139.2
Finished [100%]: Average Loss = 1,196.8
Finished [100%]: Average Loss = 1,097.2
Finished [100%]: Average Loss = 1,102.1
Finished [100%]: Average Loss = 1,219.6
Finished [100%]: Average Loss = 1,194.1
Finished [100%]: Average Loss = 1,189.6
Finished [100%]: Average Loss = 1,301.9
Finished [100%]: Average Loss = 1,202.8
Finished [100%]: Average Loss = 1,259.7
Finished [100%]: Average Loss = 1,240.5
Finished [100%]: Average Loss = 1,175
Finished [100%]: Average Loss = 1,279.8
Finished [100%]: Average Loss = 1,173.4
Finished [100%]: Average Loss = 1,173.9
Finished [100%]: Average Loss = 1,126.8
Finished [100%]: Average Loss = 1,272.7
Finished [100%]: Average Loss = 1,386.9
Finished [100%]: Average Loss = 1,298.9
Finished [100%]: Average Loss = 1,256.9
Finished [100%]: Average Loss = 1,251.4
Finished [100%]: Average Loss = 1,163.5
Finished [100%]: Average Loss = 1,200.6
Finished [100%]: Average Loss = 1,029.7
Finished [100%]: Average Loss = 1,177.6
Finished [100%]: Average Loss = 1,073.4
Finished [100%]: Average Loss = 1,008.7
Finished [100%]: Average Loss = 1,048.2
Finished [100%]: Average Loss = 1,099.4
Finished [100%]: Average Loss = 1,025.5
Finished [100%]: Average Loss = 956.76
Finished [100%]: Average Loss = 1,004.1
Finished [100%]: Average Loss = 1,160.9
Finished [100%]: Average Loss = 1,191
Finished [100%]: Average Loss = 1,338.7
Finished [100%]: Average Loss = 1,234.3
Finished [100%]: Average Loss = 1,276.3
Finished [100%]: Average Loss = 1,167.3
Finished [100%]: Average Loss = 1,206.7
Finished [100%]: Average Loss = 1,255.7
Finished [100%]: Average Loss = 1,050.2
Finished [100%]: Average Loss = 1,288.1
Finished [100%]: Average Loss = 1,285.5
Finished [100%]: Average Loss = 1,281.3
Finished [100%]: Average Loss = 1,157
Finished [100%]: Average Loss = 1,133.2
Finished [100%]: Average Loss = 1,216.3
Finished [100%]: Average Loss = 1,076.6
Finished [100%]: Average Loss = 804.39
Finished [100%]: Average Loss = 663.65
Finished [100%]: Average Loss = 1,005.3
Finished [100%]: Average Loss = 1,176.9
Finished [100%]: Average Loss = 1,071
Finished [100%]: Average Loss = 1,062.3
Finished [100%]: Average Loss = 1,156.8
Finished [100%]: Average Loss = 1,345.4
Finished [100%]: Average Loss = 1,512.9
Finished [100%]: Average Loss = 1,533.6
Finished [100%]: Average Loss = 1,356.6
Finished [100%]: Average Loss = 1,309.4
Finished [100%]: Average Loss = 1,310.4
Finished [100%]: Average Loss = 1,312.6
Finished [100%]: Average Loss = 1,296.2
Finished [100%]: Average Loss = 1,157.3
Finished [100%]: Average Loss = 1,332.8
Finished [100%]: Average Loss = 1,085.5
Finished [100%]: Average Loss = 1,274.9
Finished [100%]: Average Loss = 1,200.9
Finished [100%]: Average Loss = 1,142
Finished [100%]: Average Loss = 1,252.7
Finished [100%]: Average Loss = 1,130.3
Finished [100%]: Average Loss = 1,144.2
Finished [100%]: Average Loss = 1,290.6
Finished [100%]: Average Loss = 1,050.7
Finished [100%]: Average Loss = 1,067.9
Finished [100%]: Average Loss = 988.74
Finished [100%]: Average Loss = 905.48
Finished [100%]: Average Loss = 739.01
Finished [100%]: Average Loss = 1,060.1
Finished [100%]: Average Loss = 877.84
Finished [100%]: Average Loss = 868.03
Finished [100%]: Average Loss = 766.98
Finished [100%]: Average Loss = 901.99
Finished [100%]: Average Loss = 647.46
Finished [100%]: Average Loss = 985.45
Finished [100%]: Average Loss = 1,066.8
Finished [100%]: Average Loss = 1,108.7
Finished [100%]: Average Loss = 1,200.7
Finished [100%]: Average Loss = 1,186.5
Finished [100%]: Average Loss = 1,214.9
Finished [100%]: Average Loss = 1,153
Finished [100%]: Average Loss = 1,276.5
Finished [100%]: Average Loss = 1,131.9
Finished [100%]: Average Loss = 1,007.6
Finished [100%]: Average Loss = 1,263.3
Finished [100%]: Average Loss = 1,135.8
Finished [100%]: Average Loss = 1,126.3
Finished [100%]: Average Loss = 1,118.7
Finished [100%]: Average Loss = 1,147.9
Finished [100%]: Average Loss = 844.52
Finished [100%]: Average Loss = 496.99
Finished [100%]: Average Loss = 675.31
Finished [100%]: Average Loss = 951.99
Finished [100%]: Average Loss = 1,005.9
Finished [100%]: Average Loss = 1,109.7
Finished [100%]: Average Loss = 846.22
Finished [100%]: Average Loss = 1,162.7
Finished [100%]: Average Loss = 1,058.4
Finished [100%]: Average Loss = 1,352.6
Finished [100%]: Average Loss = 1,272.6
Finished [100%]: Average Loss = 1,324.3
Finished [100%]: Average Loss = 1,275.6
Finished [100%]: Average Loss = 1,312.9
Finished [100%]: Average Loss = 1,080.1
Finished [100%]: Average Loss = 992.95
Finished [100%]: Average Loss = 924.3
Finished [100%]: Average Loss = 1,041.7
Finished [100%]: Average Loss = 1,085.3
Finished [100%]: Average Loss = 1,198.5
Finished [100%]: Average Loss = 1,051.5
Finished [100%]: Average Loss = 1,223.5
Finished [100%]: Average Loss = 1,157.1
Finished [100%]: Average Loss = 1,161.1
Finished [100%]: Average Loss = 1,191.2
Finished [100%]: Average Loss = 1,102
Finished [100%]: Average Loss = 1,091.3
Finished [100%]: Average Loss = 1,057.3
Finished [100%]: Average Loss = 907.35
Finished [100%]: Average Loss = 982.63
Finished [100%]: Average Loss = 1,036.6
Finished [100%]: Average Loss = 990.45
Finished [100%]: Average Loss = 900.55
Finished [100%]: Average Loss = 866.31
Finished [100%]: Average Loss = 802.75
Finished [100%]: Average Loss = 960.43
Finished [100%]: Average Loss = 1,067.7
Finished [100%]: Average Loss = 1,098.1
Finished [100%]: Average Loss = 1,187.1
Finished [100%]: Average Loss = 1,125.4
Finished [100%]: Average Loss = 1,110.7
Finished [100%]: Average Loss = 1,127.5
Finished [100%]: Average Loss = 1,227.6
Finished [100%]: Average Loss = 1,312.2
Finished [100%]: Average Loss = 1,304.8
Finished [100%]: Average Loss = 1,161.4
Finished [100%]: Average Loss = 1,145.8
Finished [100%]: Average Loss = 1,156.1
Finished [100%]: Average Loss = 1,317.3
Finished [100%]: Average Loss = 1,139.2
Finished [100%]: Average Loss = 1,013.2
Finished [100%]: Average Loss = 1,200.8
Finished [100%]: Average Loss = 1,078.4
Finished [100%]: Average Loss = 670.28
Finished [100%]: Average Loss = 771.57
Finished [100%]: Average Loss = 1,115.6
Finished [100%]: Average Loss = 1,118.9
Finished [100%]: Average Loss = 1,320.2
Finished [100%]: Average Loss = 1,345.7
Finished [100%]: Average Loss = 1,361.7
Finished [100%]: Average Loss = 1,239.2
Finished [100%]: Average Loss = 1,232.4
Finished [100%]: Average Loss = 1,458.2
Finished [100%]: Average Loss = 1,357.7
Finished [100%]: Average Loss = 1,070.2
Finished [100%]: Average Loss = 1,183.7
Finished [100%]: Average Loss = 1,080.2
Finished [100%]: Average Loss = 967.06
Finished [100%]: Average Loss = 1,099.9
Finished [100%]: Average Loss = 1,042.3
Finished [100%]: Average Loss = 1,144.8
Finished [100%]: Average Loss = 1,203.6
Finished [100%]: Average Loss = 1,048.9
Finished [100%]: Average Loss = 1,264.2
Finished [100%]: Average Loss = 1,237.9
Finished [100%]: Average Loss = 1,136.2
Finished [100%]: Average Loss = 1,083.6
Finished [100%]: Average Loss = 1,069.7
Finished [100%]: Average Loss = 989.3
Finished [100%]: Average Loss = 1,014.6
Finished [100%]: Average Loss = 957.78
Finished [100%]: Average Loss = 970.33
Finished [100%]: Average Loss = 880.03
Finished [100%]: Average Loss = 926.74
Finished [100%]: Average Loss = 990.86
Finished [100%]: Average Loss = 992.63
Finished [100%]: Average Loss = 995.52
Finished [100%]: Average Loss = 973.27
Finished [100%]: Average Loss = 1,069.1
Finished [100%]: Average Loss = 1,181.1
Finished [100%]: Average Loss = 1,132.5
Finished [100%]: Average Loss = 1,235.1
Finished [100%]: Average Loss = 1,267.7
Finished [100%]: Average Loss = 1,172
Finished [100%]: Average Loss = 1,294
Finished [100%]: Average Loss = 1,201.1
Finished [100%]: Average Loss = 1,049.1
Finished [100%]: Average Loss = 1,288.4
Finished [100%]: Average Loss = 1,062.2
Finished [100%]: Average Loss = 1,192.6
Finished [100%]: Average Loss = 1,309.1
Finished [100%]: Average Loss = 1,210.5
Finished [100%]: Average Loss = 1,108.8
Finished [100%]: Average Loss = 1,215.5
Finished [100%]: Average Loss = 1,110.9
Finished [100%]: Average Loss = 764.31
Finished [100%]: Average Loss = 592.13
Finished [100%]: Average Loss = 1,024.6
Finished [100%]: Average Loss = 1,047.3
Finished [100%]: Average Loss = 1,104.4
Finished [100%]: Average Loss = 1,238.3
Finished [100%]: Average Loss = 1,208.4
Finished [100%]: Average Loss = 1,135
Finished [100%]: Average Loss = 1,204.9
Finished [100%]: Average Loss = 1,340.5
Finished [100%]: Average Loss = 1,086.4
Finished [100%]: Average Loss = 1,267.5
Finished [100%]: Average Loss = 1,164.9
Finished [100%]: Average Loss = 1,267.6
Finished [100%]: Average Loss = 1,199
Finished [100%]: Average Loss = 1,262.5
Finished [100%]: Average Loss = 991.67
Finished [100%]: Average Loss = 1,096.5
Finished [100%]: Average Loss = 1,229.6
Finished [100%]: Average Loss = 1,055.4
Finished [100%]: Average Loss = 1,165.4
Finished [100%]: Average Loss = 1,184.5
Finished [100%]: Average Loss = 1,040.1
Finished [100%]: Average Loss = 1,049.2
Finished [100%]: Average Loss = 1,165.7
Finished [100%]: Average Loss = 1,188.7
Finished [100%]: Average Loss = 800.68

Total time: 1042.2 seconds
Weeks fit: 391
Weeks skipped: 0

In [12]:
weeklyMetricsEuropeDF = pd.DataFrame(weeklyMetricsEurope)
print(weeklyMetricsEuropeDF[['week', 'entropy']].describe())

          entropy
count  391.000000
mean     5.991465
std      0.000000
min      5.991465
25%      5.991465
50%      5.991465
75%      5.991465
max      5.991465

In [13]:
sampleWeek1 = weeklyMetricsEurope[0]
sampleWeek2 = weeklyMetricsEurope[200]

print(sampleWeek1['week'], sampleWeek1['entropy'])
print(sampleWeek2['week'], sampleWeek2['entropy'])
print(sampleWeek1['flipProbabilities'] == sampleWeek2['flipProbabilities'])

2018-01-01/2018-01-07 5.991464547107983
2021-11-01/2021-11-07 5.991464547107983
False

In [14]:
import numpy as np
from scipy.stats import entropy as entropyFunc

def diagnosticEntropy(trace, nCountries): 
    samples = trace.posterior['beta'].values.reshape(-1, nCountries)
    rankings = np.argsort(-samples, axis=1)
    uniqueRankings, counts = np.unique(rankings, axis=0, return_counts=True)
    probabilities = counts /counts.sum()
    return len(uniqueRankings), counts.max(), entropyFunc(probabilities)                                                    

diagnosticWeeks = ['2018-01-01/2018-01-07', '2021-11-01/2021-11-07']

for week in diagnosticWeeks:
    weekPeriod = pd.Period(week, freq='W-SUN')
    weekData = europeData[europeData['week'] == weekPeriod]

    indexI = weekData['countryI'].map(europeIndexMap).to_numpy()
    indexJ = weekData['countryJ'].map(europeIndexMap).to_numpy()
    winsI = weekData['winsI'].to_numpy()
    totals = weekData['total'].to_numpy()

    with rollingModelEurope:
        pm.set_data({
            'indexIData': indexI,
            'indexJData': indexJ,
            'winsIData': winsI,
            'totalsData': totals
        })

        approx = pm.fit(n=20000, method='advi', progressbar=False)
        trace = approx.sample(400)

    nUnique, maxCount, ent = diagnosticEntropy(trace, nEuropeCountries)
    print(f"{week}: unique rankings = {nUnique} out of 400 draws, max single-ranking count = {maxCount}, entropy = {ent:.4f}")

Finished [100%]: Average Loss = 47.995

2018-01-01/2018-01-07: unique rankings = 400 out of 400 draws, max single-ranking count = 1, entropy = 5.9915

Finished [100%]: Average Loss = 1,049.9

2021-11-01/2021-11-07: unique rankings = 400 out of 400 draws, max single-ranking count = 1, entropy = 5.9915

In [17]:
longRowsEurope = []

for _, row in weeklyMetricsEuropeDF.iterrows():
    week = row['week']
    region = row['region']
    entropy = row['entropy']

    flipProbs = parseMetricDict(row['flipProbabilities'])
    hdiOverlaps = parseMetricDict(row['hdiOverlaps'])

    for pairLabel, flipProb in flipProbs.items():
        countryI, countryJ = pairLabel.split(' over ')
        overlap = hdiOverlaps.get(f"{countryI} vs {countryJ}", None)

        longRowsEurope.append({
            'week': week,
            'region': region,
            'entropy': entropy,
            'entropyReliable': False,
            'countryI': countryI,
            'countryJ': countryJ,
            'flipProbability': flipProb,
            'hdiOverlap': overlap
        })

longFormEuropeDF = pd.DataFrame(longRowsEurope)
print(longFormEuropeDF.shape)

(320620, 8)

In [18]:
longFormEuropeDF.to_csv('../Data/Processed/weeklyUncertaintyEurope.csv', index=False)