In [2]:
import pandas as pd
import numpy as np
import itertools
import pymc as pm
import arviz as az
import time

import sys
sys.path.append('../Source')
from Pipeline.build_country_comparisons import buildCountryComparisons

alignedCountryData = pd.read_csv('../Data/Processed/alignedDataCountry.csv')
countryComparisons = buildCountryComparisons(alignedCountryData)

caucasusData = countryComparisons[countryComparisons['region'] == 'Caucasus and Central Asia']
regionCountries = sorted(set(caucasusData['countryI']) | set(caucasusData['countryJ']))
regionIndexMap = {country: i for i, country in enumerate(regionCountries)}
nRegionCountries = len(regionCountries)
caucasusWeeks = sorted(caucasusData['week'].unique())

print(nRegionCountries, len(caucasusWeeks))

c:\Users\rcuhl\miniconda3\envs\georisk\Lib\site-packages\arviz\__init__.py:50: FutureWarning:
ArviZ is undergoing a major refactor to improve flexibility and extensibility while maintaining a user-friendly interface.
Some upcoming changes may be backward incompatible.
For details and migration guidance, visit: https://python.arviz.org/en/latest/user_guide/migration_guide.html
  warn(

9 391

In [2]:
initialWeekData = caucasusData[caucasusData['week'] == 0]

initialIndexI = caucasusData['countryI'].map(regionIndexMap).to_numpy()
initialIndexJ = caucasusData['countryJ'].map(regionIndexMap).to_numpy()
initialWinsI = caucasusData['winsI'].to_numpy()
initialTotals = caucasusData['total'].to_numpy()

with pm.Model() as rollingModel:
    indexIData = pm.Data('indexIData', initialIndexI)
    indexJData = pm.Data('indexJData', initialIndexJ)
    winsIData = pm.Data('winsIData', initialWinsI)
    totalsData = pm.Data('totalsData', initialTotals)

    beta = pm.ZeroSumNormal('beta', sigma=1.0, shape=nRegionCountries)
    probability = pm.math.sigmoid(beta[indexIData] - beta[indexJData])
    obs = pm.Binomial('obs', n=totalsData, p=probability, observed=winsIData)

In [3]:
weeklyBetaResults = []
weeksSkipped = []

startTime = time.time()

for week in caucasusWeeks:
    weekData = caucasusData[caucasusData['week'] == week]

    if len(weekData) == 0:
        weeksSkipped.append(week)
        continue

    indexI = weekData['countryI'].map(regionIndexMap).to_numpy()
    indexJ = weekData['countryJ'].map(regionIndexMap).to_numpy()
    winsI = weekData['winsI'].to_numpy()
    totals = weekData['total'].to_numpy()

    with rollingModel:
        pm.set_data({
            'indexIData': indexI,
            'indexJData': indexJ,
            'winsIData': winsI,
            'totalsData': totals
        })

        approx = pm.fit(n=20000, method='advi', progressbar=False)
        trace = approx.sample(400)

    betaSamples = trace.posterior['beta'].values.reshape(-1, nRegionCountries)
    betaMeans = betaSamples.mean(axis=0)
    betaStds = betaSamples.std(axis=0)

    for i, country in enumerate(regionCountries):
        weeklyBetaResults.append({
            'week': week,
            'region': 'Caucasus and Central Asia',
            'country': country,
            'betaMean': betaMeans[i],
            'betaStd': betaStds[i]
        })

endTime = time.time()

print(f"Total time: {endTime - startTime:.1f} seconds")
print(f"Weeks fit: {len(caucasusWeeks) - len(weeksSkipped)}")
print(f"Weeks skipped: {len(weeksSkipped)}")

Finished [100%]: Average Loss = 48.594
Finished [100%]: Average Loss = 61.498
Finished [100%]: Average Loss = 48.743
Finished [100%]: Average Loss = 61.644
Finished [100%]: Average Loss = 60.794
Finished [100%]: Average Loss = 63.605
Finished [100%]: Average Loss = 49.471
Finished [100%]: Average Loss = 50.007
Finished [100%]: Average Loss = 50.103
Finished [100%]: Average Loss = 72.581
Finished [100%]: Average Loss = 60.64
Finished [100%]: Average Loss = 60.138
Finished [100%]: Average Loss = 59.489
Finished [100%]: Average Loss = 75.164
Finished [100%]: Average Loss = 63.87
Finished [100%]: Average Loss = 51.686
Finished [100%]: Average Loss = 64.344
Finished [100%]: Average Loss = 73.337
Finished [100%]: Average Loss = 65.258
Finished [100%]: Average Loss = 51.385
Finished [100%]: Average Loss = 61.115
Finished [100%]: Average Loss = 63.973
Finished [100%]: Average Loss = 76.455
Finished [100%]: Average Loss = 60.533
Finished [100%]: Average Loss = 50.795
Finished [100%]: Average Loss = 50.356
Finished [100%]: Average Loss = 49.339
Finished [100%]: Average Loss = 47.636
Finished [100%]: Average Loss = 59.43
Finished [100%]: Average Loss = 66.549
Finished [100%]: Average Loss = 48.865
Finished [100%]: Average Loss = 50.046
Finished [100%]: Average Loss = 60.472
Finished [100%]: Average Loss = 36.815
Finished [100%]: Average Loss = 69.581
Finished [100%]: Average Loss = 62.887
Finished [100%]: Average Loss = 60.797
Finished [100%]: Average Loss = 61.886
Finished [100%]: Average Loss = 62.67
Finished [100%]: Average Loss = 71.789
Finished [100%]: Average Loss = 49.009
Finished [100%]: Average Loss = 58.871
Finished [100%]: Average Loss = 47.546
Finished [100%]: Average Loss = 46.071
Finished [100%]: Average Loss = 69.618
Finished [100%]: Average Loss = 44.858
Finished [100%]: Average Loss = 47.697
Finished [100%]: Average Loss = 67.718
Finished [100%]: Average Loss = 68.47
Finished [100%]: Average Loss = 56.928
Finished [100%]: Average Loss = 47.691
Finished [100%]: Average Loss = 46.819
Finished [100%]: Average Loss = 53.374
Finished [100%]: Average Loss = 53.268
Finished [100%]: Average Loss = 46.85
Finished [100%]: Average Loss = 56.36
Finished [100%]: Average Loss = 46.531
Finished [100%]: Average Loss = 46.501
Finished [100%]: Average Loss = 58.561
Finished [100%]: Average Loss = 46.057
Finished [100%]: Average Loss = 59.31
Finished [100%]: Average Loss = 66.994
Finished [100%]: Average Loss = 59.682
Finished [100%]: Average Loss = 59.166
Finished [100%]: Average Loss = 70.452
Finished [100%]: Average Loss = 67.964
Finished [100%]: Average Loss = 59.153
Finished [100%]: Average Loss = 65.754
Finished [100%]: Average Loss = 62.316
Finished [100%]: Average Loss = 60.813
Finished [100%]: Average Loss = 70.254
Finished [100%]: Average Loss = 60.576
Finished [100%]: Average Loss = 72.07
Finished [100%]: Average Loss = 73.59
Finished [100%]: Average Loss = 59.299
Finished [100%]: Average Loss = 69.532
Finished [100%]: Average Loss = 62.532
Finished [100%]: Average Loss = 58.765
Finished [100%]: Average Loss = 70.014
Finished [100%]: Average Loss = 68.317
Finished [100%]: Average Loss = 73.544
Finished [100%]: Average Loss = 72.176
Finished [100%]: Average Loss = 60.802
Finished [100%]: Average Loss = 78.11
Finished [100%]: Average Loss = 48.439
Finished [100%]: Average Loss = 69.124
Finished [100%]: Average Loss = 60.963
Finished [100%]: Average Loss = 91.22
Finished [100%]: Average Loss = 74.316
Finished [100%]: Average Loss = 73.524
Finished [100%]: Average Loss = 75.822
Finished [100%]: Average Loss = 90.255
Finished [100%]: Average Loss = 62.985
Finished [100%]: Average Loss = 75.573
Finished [100%]: Average Loss = 62.601
Finished [100%]: Average Loss = 60.999
Finished [100%]: Average Loss = 71.146
Finished [100%]: Average Loss = 63.01
Finished [100%]: Average Loss = 62.591
Finished [100%]: Average Loss = 62.005
Finished [100%]: Average Loss = 62.184
Finished [100%]: Average Loss = 60.881
Finished [100%]: Average Loss = 48.497
Finished [100%]: Average Loss = 50.097
Finished [100%]: Average Loss = 66.397
Finished [100%]: Average Loss = 58.757
Finished [100%]: Average Loss = 61.729
Finished [100%]: Average Loss = 72.19
Finished [100%]: Average Loss = 62.351
Finished [100%]: Average Loss = 48.827
Finished [100%]: Average Loss = 59.027
Finished [100%]: Average Loss = 62.669
Finished [100%]: Average Loss = 59.36
Finished [100%]: Average Loss = 72.196
Finished [100%]: Average Loss = 62.214
Finished [100%]: Average Loss = 48.119
Finished [100%]: Average Loss = 53.72
Finished [100%]: Average Loss = 66.235
Finished [100%]: Average Loss = 42.843
Finished [100%]: Average Loss = 45.648
Finished [100%]: Average Loss = 53.587
Finished [100%]: Average Loss = 44.132
Finished [100%]: Average Loss = 53.797
Finished [100%]: Average Loss = 80.609
Finished [100%]: Average Loss = 69.529
Finished [100%]: Average Loss = 71.675
Finished [100%]: Average Loss = 81.832
Finished [100%]: Average Loss = 58.662
Finished [100%]: Average Loss = 86.397
Finished [100%]: Average Loss = 62.217
Finished [100%]: Average Loss = 69.513
Finished [100%]: Average Loss = 64.297
Finished [100%]: Average Loss = 63.189
Finished [100%]: Average Loss = 64.846
Finished [100%]: Average Loss = 74.726
Finished [100%]: Average Loss = 76.454
Finished [100%]: Average Loss = 84.47
Finished [100%]: Average Loss = 63.921
Finished [100%]: Average Loss = 75.732
Finished [100%]: Average Loss = 85.177
Finished [100%]: Average Loss = 60.978
Finished [100%]: Average Loss = 64.498
Finished [100%]: Average Loss = 83.58
Finished [100%]: Average Loss = 72.008
Finished [100%]: Average Loss = 73.955
Finished [100%]: Average Loss = 74.07
Finished [100%]: Average Loss = 61.42
Finished [100%]: Average Loss = 72.945
Finished [100%]: Average Loss = 74.255
Finished [100%]: Average Loss = 63.631
Finished [100%]: Average Loss = 53.439
Finished [100%]: Average Loss = 55.888
Finished [100%]: Average Loss = 54.55
Finished [100%]: Average Loss = 58.743
Finished [100%]: Average Loss = 57.974
Finished [100%]: Average Loss = 53.68
Finished [100%]: Average Loss = 51.758
Finished [100%]: Average Loss = 50.364
Finished [100%]: Average Loss = 57.121
Finished [100%]: Average Loss = 55.846
Finished [100%]: Average Loss = 68.538
Finished [100%]: Average Loss = 59.485
Finished [100%]: Average Loss = 60.02
Finished [100%]: Average Loss = 66.165
Finished [100%]: Average Loss = 57.801
Finished [100%]: Average Loss = 68.732
Finished [100%]: Average Loss = 58.193
Finished [100%]: Average Loss = 58.792
Finished [100%]: Average Loss = 53.562
Finished [100%]: Average Loss = 52.826
Finished [100%]: Average Loss = 60.638
Finished [100%]: Average Loss = 58.701
Finished [100%]: Average Loss = 60.703
Finished [100%]: Average Loss = 74.966
Finished [100%]: Average Loss = 55.825
Finished [100%]: Average Loss = 60.335
Finished [100%]: Average Loss = 70.951
Finished [100%]: Average Loss = 72.348
Finished [100%]: Average Loss = 60.137
Finished [100%]: Average Loss = 41.668
Finished [100%]: Average Loss = 57.336
Finished [100%]: Average Loss = 65.058
Finished [100%]: Average Loss = 54.445
Finished [100%]: Average Loss = 57.404
Finished [100%]: Average Loss = 66.765
Finished [100%]: Average Loss = 53.538
Finished [100%]: Average Loss = 64.137
Finished [100%]: Average Loss = 56.839
Finished [100%]: Average Loss = 54.733
Finished [100%]: Average Loss = 52.425
Finished [100%]: Average Loss = 50.972
Finished [100%]: Average Loss = 47.124
Finished [100%]: Average Loss = 49.403
Finished [100%]: Average Loss = 54.361
Finished [100%]: Average Loss = 59.59
Finished [100%]: Average Loss = 56.558
Finished [100%]: Average Loss = 47.336
Finished [100%]: Average Loss = 49.735
Finished [100%]: Average Loss = 36.126
Finished [100%]: Average Loss = 43.702
Finished [100%]: Average Loss = 46.88
Finished [100%]: Average Loss = 47.398
Finished [100%]: Average Loss = 65.356
Finished [100%]: Average Loss = 59.269
Finished [100%]: Average Loss = 61.262
Finished [100%]: Average Loss = 51.098
Finished [100%]: Average Loss = 46.97
Finished [100%]: Average Loss = 42.993
Finished [100%]: Average Loss = 48.126
Finished [100%]: Average Loss = 45.747
Finished [100%]: Average Loss = 61.206
Finished [100%]: Average Loss = 47.045
Finished [100%]: Average Loss = 60.516
Finished [100%]: Average Loss = 49.935
Finished [100%]: Average Loss = 48.674
Finished [100%]: Average Loss = 53.846
Finished [100%]: Average Loss = 51.525
Finished [100%]: Average Loss = 50.199
Finished [100%]: Average Loss = 63.939
Finished [100%]: Average Loss = 45.989
Finished [100%]: Average Loss = 45.45
Finished [100%]: Average Loss = 38.563
Finished [100%]: Average Loss = 49.377
Finished [100%]: Average Loss = 48.151
Finished [100%]: Average Loss = 54.939
Finished [100%]: Average Loss = 48.945
Finished [100%]: Average Loss = 52.328
Finished [100%]: Average Loss = 68.465
Finished [100%]: Average Loss = 66.438
Finished [100%]: Average Loss = 57.142
Finished [100%]: Average Loss = 61.988
Finished [100%]: Average Loss = 57.277
Finished [100%]: Average Loss = 62.435
Finished [100%]: Average Loss = 52.498
Finished [100%]: Average Loss = 48.466
Finished [100%]: Average Loss = 47.294
Finished [100%]: Average Loss = 44.11
Finished [100%]: Average Loss = 44.018
Finished [100%]: Average Loss = 46.769
Finished [100%]: Average Loss = 48.48
Finished [100%]: Average Loss = 49.154
Finished [100%]: Average Loss = 50.347
Finished [100%]: Average Loss = 49.791
Finished [100%]: Average Loss = 56.443
Finished [100%]: Average Loss = 44.719
Finished [100%]: Average Loss = 75.342
Finished [100%]: Average Loss = 60.43
Finished [100%]: Average Loss = 46.845
Finished [100%]: Average Loss = 38.867
Finished [100%]: Average Loss = 52.791
Finished [100%]: Average Loss = 39.278
Finished [100%]: Average Loss = 43.375
Finished [100%]: Average Loss = 32.514
Finished [100%]: Average Loss = 47.102
Finished [100%]: Average Loss = 46.782
Finished [100%]: Average Loss = 51.388
Finished [100%]: Average Loss = 38.651
Finished [100%]: Average Loss = 46.278
Finished [100%]: Average Loss = 48.913
Finished [100%]: Average Loss = 58.401
Finished [100%]: Average Loss = 52.909
Finished [100%]: Average Loss = 41.452
Finished [100%]: Average Loss = 42.741
Finished [100%]: Average Loss = 44.956
Finished [100%]: Average Loss = 43.559
Finished [100%]: Average Loss = 54.123
Finished [100%]: Average Loss = 41.825
Finished [100%]: Average Loss = 43.981
Finished [100%]: Average Loss = 46.311
Finished [100%]: Average Loss = 45.596
Finished [100%]: Average Loss = 64.64
Finished [100%]: Average Loss = 56.417
Finished [100%]: Average Loss = 51.347
Finished [100%]: Average Loss = 49.737
Finished [100%]: Average Loss = 43.256
Finished [100%]: Average Loss = 49.522
Finished [100%]: Average Loss = 35.186
Finished [100%]: Average Loss = 67.001
Finished [100%]: Average Loss = 34.72
Finished [100%]: Average Loss = 45.333
Finished [100%]: Average Loss = 42.317
Finished [100%]: Average Loss = 51.33
Finished [100%]: Average Loss = 46.077
Finished [100%]: Average Loss = 48.91
Finished [100%]: Average Loss = 46.035
Finished [100%]: Average Loss = 51.809
Finished [100%]: Average Loss = 32.936
Finished [100%]: Average Loss = 42.507
Finished [100%]: Average Loss = 50.121
Finished [100%]: Average Loss = 45.252
Finished [100%]: Average Loss = 44.605
Finished [100%]: Average Loss = 43.681
Finished [100%]: Average Loss = 34.158
Finished [100%]: Average Loss = 49.887
Finished [100%]: Average Loss = 47.427
Finished [100%]: Average Loss = 44.136
Finished [100%]: Average Loss = 38.551
Finished [100%]: Average Loss = 47.316
Finished [100%]: Average Loss = 53.664
Finished [100%]: Average Loss = 46.814
Finished [100%]: Average Loss = 41.79
Finished [100%]: Average Loss = 42.135
Finished [100%]: Average Loss = 41.176
Finished [100%]: Average Loss = 31.179
Finished [100%]: Average Loss = 41.176
Finished [100%]: Average Loss = 30.627
Finished [100%]: Average Loss = 37.25
Finished [100%]: Average Loss = 40.075
Finished [100%]: Average Loss = 32.586
Finished [100%]: Average Loss = 31.397
Finished [100%]: Average Loss = 42.658
Finished [100%]: Average Loss = 37.064
Finished [100%]: Average Loss = 34.528
Finished [100%]: Average Loss = 25.582
Finished [100%]: Average Loss = 30.24
Finished [100%]: Average Loss = 37.802
Finished [100%]: Average Loss = 35.437
Finished [100%]: Average Loss = 31.245
Finished [100%]: Average Loss = 31.152
Finished [100%]: Average Loss = 37.49
Finished [100%]: Average Loss = 41.433
Finished [100%]: Average Loss = 36.909
Finished [100%]: Average Loss = 42.712
Finished [100%]: Average Loss = 43.475
Finished [100%]: Average Loss = 35.271
Finished [100%]: Average Loss = 28.8
Finished [100%]: Average Loss = 55.769
Finished [100%]: Average Loss = 53.923
Finished [100%]: Average Loss = 46.046
Finished [100%]: Average Loss = 46.125
Finished [100%]: Average Loss = 28.479
Finished [100%]: Average Loss = 46.373
Finished [100%]: Average Loss = 59.285
Finished [100%]: Average Loss = 53.045
Finished [100%]: Average Loss = 33.273
Finished [100%]: Average Loss = 32.917
Finished [100%]: Average Loss = 54.515
Finished [100%]: Average Loss = 47.983
Finished [100%]: Average Loss = 45.738
Finished [100%]: Average Loss = 39.949
Finished [100%]: Average Loss = 23.926
Finished [100%]: Average Loss = 42.683
Finished [100%]: Average Loss = 39.029
Finished [100%]: Average Loss = 36.301
Finished [100%]: Average Loss = 27.862
Finished [100%]: Average Loss = 28.336
Finished [100%]: Average Loss = 37.42
Finished [100%]: Average Loss = 36.642
Finished [100%]: Average Loss = 31.474
Finished [100%]: Average Loss = 40.071
Finished [100%]: Average Loss = 32.931
Finished [100%]: Average Loss = 36.612
Finished [100%]: Average Loss = 36.165
Finished [100%]: Average Loss = 38.713
Finished [100%]: Average Loss = 36.297
Finished [100%]: Average Loss = 38.692
Finished [100%]: Average Loss = 40.378
Finished [100%]: Average Loss = 31.501
Finished [100%]: Average Loss = 44.602
Finished [100%]: Average Loss = 51.694
Finished [100%]: Average Loss = 31.269
Finished [100%]: Average Loss = 35.275
Finished [100%]: Average Loss = 32.391
Finished [100%]: Average Loss = 40.198
Finished [100%]: Average Loss = 40.542
Finished [100%]: Average Loss = 39.917
Finished [100%]: Average Loss = 49.803
Finished [100%]: Average Loss = 46.427
Finished [100%]: Average Loss = 36.451
Finished [100%]: Average Loss = 43.099
Finished [100%]: Average Loss = 43.978
Finished [100%]: Average Loss = 45.249
Finished [100%]: Average Loss = 45.94
Finished [100%]: Average Loss = 32.895
Finished [100%]: Average Loss = 47.876
Finished [100%]: Average Loss = 38.327
Finished [100%]: Average Loss = 35.081
Finished [100%]: Average Loss = 42.218
Finished [100%]: Average Loss = 34.407
Finished [100%]: Average Loss = 46.552
Finished [100%]: Average Loss = 44.417
Finished [100%]: Average Loss = 40.762
Finished [100%]: Average Loss = 44.074
Finished [100%]: Average Loss = 32.636
Finished [100%]: Average Loss = 41.626
Finished [100%]: Average Loss = 43.449
Finished [100%]: Average Loss = 33.58
Finished [100%]: Average Loss = 32.407
Finished [100%]: Average Loss = 22.397
Finished [100%]: Average Loss = 43.686
Finished [100%]: Average Loss = 25.186

Total time: 1159.3 seconds
Weeks fit: 391
Weeks skipped: 0

In [4]:
weeklyBetaCaucasusDF = pd.DataFrame(weeklyBetaResults)
print(weeklyBetaCaucasusDF.shape)
weeklyBetaCaucasusDF.head(10)

(3519, 5)

,week,region,country,betaMean,betaStd
0,2018-01-01/2018-01-07,Caucasus and Central Asia,Afghanistan,2.221638,0.163267
1,2018-01-01/2018-01-07,Caucasus and Central Asia,Armenia,-0.332028,0.222841
2,2018-01-01/2018-01-07,Caucasus and Central Asia,Azerbaijan,2.187950,0.164607
3,2018-01-01/2018-01-07,Caucasus and Central Asia,Georgia,-0.234997,0.237734
4,2018-01-01/2018-01-07,Caucasus and Central Asia,Kazakhstan,-1.113216,0.284975
5,2018-01-01/2018-01-07,Caucasus and Central Asia,Kyrgyzstan,-1.978129,0.390205
6,2018-01-01/2018-01-07,Caucasus and Central Asia,Tajikistan,0.560879,0.885285
7,2018-01-01/2018-01-07,Caucasus and Central Asia,Turkmenistan,0.620993,0.831263
8,2018-01-01/2018-01-07,Caucasus and Central Asia,Uzbekistan,-1.933090,0.471682
9,2018-01-08/2018-01-14,Caucasus and Central Asia,Afghanistan,2.404007,0.127639

In [5]:
weeklyBetaCaucasusDF.to_csv('../Data/Processed/weeklyBetaCaucasusCA.csv', index=False)

In [6]:
middleEastData = countryComparisons[countryComparisons['region'] == 'Middle East']
middleEastCountries = sorted(set(middleEastData['countryI']) | set(middleEastData['countryJ']))
middleEastIndexMap = {country: i for i, country in enumerate(middleEastCountries)}
nMiddleEastCountries = len(middleEastCountries)
middleEastWeeks = sorted(middleEastData['week'].unique())

print(nMiddleEastCountries, len(middleEastWeeks))

13 391

In [7]:
initialMEWeekData = middleEastData[middleEastData['week'] == middleEastWeeks[0]]

initialMEIndexI = initialMEWeekData['countryI'].map(middleEastIndexMap).to_numpy()
initialMEIndexJ = initialMEWeekData['countryJ'].map(middleEastIndexMap).to_numpy()
initialMEWinsI = initialMEWeekData['winsI'].to_numpy()
initialMETotals = initialMEWeekData['total'].to_numpy()

with pm.Model() as middleEastRollingModel:
    indexIData = pm.Data('indexIData', initialMEIndexI)
    indexJData = pm.Data('indexJData', initialMEIndexJ)
    winsIData = pm.Data('winsIData', initialMEWinsI)
    totalsData = pm.Data('totalsData', initialMETotals)

    beta = pm.ZeroSumNormal('beta', sigma=1.0, shape=nMiddleEastCountries)
    p = pm.math.sigmoid(beta[indexIData] - beta[indexJData])
    obs = pm.Binomial('obs', n=totalsData, p=p, observed=winsIData)

In [8]:
weeklyBetaResultsME = []
weeksSkippedME = []

startTime = time.time()

for week in middleEastWeeks:
    weekData = middleEastData[middleEastData['week'] == week]

    if len(weekData) == 0:
        weeksSkippedME.append(week)
        continue

    indexI = weekData['countryI'].map(middleEastIndexMap).to_numpy()
    indexJ = weekData['countryJ'].map(middleEastIndexMap).to_numpy()
    winsI = weekData['winsI'].to_numpy()
    totals = weekData['total'].to_numpy()

    with middleEastRollingModel:
        pm.set_data({
            'indexIData': indexI,
            'indexJData': indexJ,
            'winsIData': winsI,
            'totalsData': totals
        })

        approx = pm.fit(n=20000, method='advi', progressbar=False)
        trace = approx.sample(400)

    betaSamples = trace.posterior['beta'].values.reshape(-1, nMiddleEastCountries)
    betaMeans = betaSamples.mean(axis=0)
    betaStds = betaSamples.std(axis=0)

    for i, country in enumerate(middleEastCountries):
        weeklyBetaResultsME.append({
            'week': week,
            'region': 'Middle East',
            'country': country,
            'betaMean': betaMeans[i],
            'betaStd': betaStds[i]
        })

endTime = time.time()

print(f"Total time: {endTime - startTime:.1f} seconds")
print(f"Weeks fit: {len(middleEastWeeks) - len(weeksSkippedME)}")
print(f"Weeks skipped: {len(weeksSkippedME)}")

Finished [100%]: Average Loss = 138.4
Finished [100%]: Average Loss = 168.16
Finished [100%]: Average Loss = 170.1
Finished [100%]: Average Loss = 171.09
Finished [100%]: Average Loss = 175.72
Finished [100%]: Average Loss = 174.99
Finished [100%]: Average Loss = 173.45
Finished [100%]: Average Loss = 169.88
Finished [100%]: Average Loss = 162.68
Finished [100%]: Average Loss = 170.66
Finished [100%]: Average Loss = 174.14
Finished [100%]: Average Loss = 167.44
Finished [100%]: Average Loss = 157.78
Finished [100%]: Average Loss = 178.45
Finished [100%]: Average Loss = 173.2
Finished [100%]: Average Loss = 168.9
Finished [100%]: Average Loss = 168.07
Finished [100%]: Average Loss = 165.48
Finished [100%]: Average Loss = 188.82
Finished [100%]: Average Loss = 197.27
Finished [100%]: Average Loss = 167.61
Finished [100%]: Average Loss = 171.83
Finished [100%]: Average Loss = 168.97
Finished [100%]: Average Loss = 162.22
Finished [100%]: Average Loss = 161.45
Finished [100%]: Average Loss = 168.66
Finished [100%]: Average Loss = 160.79
Finished [100%]: Average Loss = 163.47
Finished [100%]: Average Loss = 168.04
Finished [100%]: Average Loss = 168.33
Finished [100%]: Average Loss = 161.37
Finished [100%]: Average Loss = 165.31
Finished [100%]: Average Loss = 164.57
Finished [100%]: Average Loss = 146.68
Finished [100%]: Average Loss = 160.26
Finished [100%]: Average Loss = 180.98
Finished [100%]: Average Loss = 167.16
Finished [100%]: Average Loss = 157.38
Finished [100%]: Average Loss = 164.34
Finished [100%]: Average Loss = 158.79
Finished [100%]: Average Loss = 161.98
Finished [100%]: Average Loss = 165.18
Finished [100%]: Average Loss = 154.15
Finished [100%]: Average Loss = 157.96
Finished [100%]: Average Loss = 156.73
Finished [100%]: Average Loss = 164.78
Finished [100%]: Average Loss = 154.65
Finished [100%]: Average Loss = 167.35
Finished [100%]: Average Loss = 164.91
Finished [100%]: Average Loss = 161.15
Finished [100%]: Average Loss = 160.84
Finished [100%]: Average Loss = 155.61
Finished [100%]: Average Loss = 154.63
Finished [100%]: Average Loss = 172.79
Finished [100%]: Average Loss = 176.82
Finished [100%]: Average Loss = 175.22
Finished [100%]: Average Loss = 158.51
Finished [100%]: Average Loss = 156.25
Finished [100%]: Average Loss = 163.39
Finished [100%]: Average Loss = 167.15
Finished [100%]: Average Loss = 162.55
Finished [100%]: Average Loss = 169.24
Finished [100%]: Average Loss = 185.19
Finished [100%]: Average Loss = 161.83
Finished [100%]: Average Loss = 176.62
Finished [100%]: Average Loss = 156.49
Finished [100%]: Average Loss = 172.06
Finished [100%]: Average Loss = 156.69
Finished [100%]: Average Loss = 198.65
Finished [100%]: Average Loss = 187.31
Finished [100%]: Average Loss = 169.58
Finished [100%]: Average Loss = 168.36
Finished [100%]: Average Loss = 178.75
Finished [100%]: Average Loss = 168.13
Finished [100%]: Average Loss = 151.41
Finished [100%]: Average Loss = 180.77
Finished [100%]: Average Loss = 162.27
Finished [100%]: Average Loss = 188.26
Finished [100%]: Average Loss = 162.19
Finished [100%]: Average Loss = 174.97
Finished [100%]: Average Loss = 160.85
Finished [100%]: Average Loss = 175.29
Finished [100%]: Average Loss = 166.26
Finished [100%]: Average Loss = 175.23
Finished [100%]: Average Loss = 154.29
Finished [100%]: Average Loss = 160.54
Finished [100%]: Average Loss = 164.13
Finished [100%]: Average Loss = 161.45
Finished [100%]: Average Loss = 174.53
Finished [100%]: Average Loss = 157.7
Finished [100%]: Average Loss = 177.53
Finished [100%]: Average Loss = 161.18
Finished [100%]: Average Loss = 162.1
Finished [100%]: Average Loss = 147.13
Finished [100%]: Average Loss = 167.21
Finished [100%]: Average Loss = 168.86
Finished [100%]: Average Loss = 190.3
Finished [100%]: Average Loss = 193.89
Finished [100%]: Average Loss = 173.07
Finished [100%]: Average Loss = 148.75
Finished [100%]: Average Loss = 176.15
Finished [100%]: Average Loss = 166.13
Finished [100%]: Average Loss = 150.98
Finished [100%]: Average Loss = 160.43
Finished [100%]: Average Loss = 159.64
Finished [100%]: Average Loss = 158.66
Finished [100%]: Average Loss = 166.93
Finished [100%]: Average Loss = 163.38
Finished [100%]: Average Loss = 173.4
Finished [100%]: Average Loss = 168.8
Finished [100%]: Average Loss = 169.73
Finished [100%]: Average Loss = 162.1
Finished [100%]: Average Loss = 165.33
Finished [100%]: Average Loss = 181
Finished [100%]: Average Loss = 153.27
Finished [100%]: Average Loss = 174.9
Finished [100%]: Average Loss = 140.28
Finished [100%]: Average Loss = 129.77
Finished [100%]: Average Loss = 124.39
Finished [100%]: Average Loss = 131.3
Finished [100%]: Average Loss = 120.97
Finished [100%]: Average Loss = 137.1
Finished [100%]: Average Loss = 168.8
Finished [100%]: Average Loss = 135.53
Finished [100%]: Average Loss = 164.32
Finished [100%]: Average Loss = 148.82
Finished [100%]: Average Loss = 152.99
Finished [100%]: Average Loss = 157.19
Finished [100%]: Average Loss = 160.76
Finished [100%]: Average Loss = 158.52
Finished [100%]: Average Loss = 158.79
Finished [100%]: Average Loss = 177.05
Finished [100%]: Average Loss = 187.06
Finished [100%]: Average Loss = 144.53
Finished [100%]: Average Loss = 125.8
Finished [100%]: Average Loss = 135.54
Finished [100%]: Average Loss = 144.08
Finished [100%]: Average Loss = 188.67
Finished [100%]: Average Loss = 143.23
Finished [100%]: Average Loss = 153.54
Finished [100%]: Average Loss = 143.75
Finished [100%]: Average Loss = 171.19
Finished [100%]: Average Loss = 178.51
Finished [100%]: Average Loss = 166.64
Finished [100%]: Average Loss = 182.29
Finished [100%]: Average Loss = 161.66
Finished [100%]: Average Loss = 167.78
Finished [100%]: Average Loss = 188.45
Finished [100%]: Average Loss = 158.91
Finished [100%]: Average Loss = 163.89
Finished [100%]: Average Loss = 139.72
Finished [100%]: Average Loss = 174.98
Finished [100%]: Average Loss = 141.75
Finished [100%]: Average Loss = 158.74
Finished [100%]: Average Loss = 161.14
Finished [100%]: Average Loss = 154.24
Finished [100%]: Average Loss = 154.39
Finished [100%]: Average Loss = 150.7
Finished [100%]: Average Loss = 142.6
Finished [100%]: Average Loss = 158.56
Finished [100%]: Average Loss = 159.03
Finished [100%]: Average Loss = 162.78
Finished [100%]: Average Loss = 166.15
Finished [100%]: Average Loss = 169.27
Finished [100%]: Average Loss = 162.65
Finished [100%]: Average Loss = 169.41
Finished [100%]: Average Loss = 176.44
Finished [100%]: Average Loss = 198.35
Finished [100%]: Average Loss = 176.56
Finished [100%]: Average Loss = 157.79
Finished [100%]: Average Loss = 175.55
Finished [100%]: Average Loss = 173.25
Finished [100%]: Average Loss = 184.97
Finished [100%]: Average Loss = 198.92
Finished [100%]: Average Loss = 190.59
Finished [100%]: Average Loss = 231.21
Finished [100%]: Average Loss = 224.25
Finished [100%]: Average Loss = 182.03
Finished [100%]: Average Loss = 156.71
Finished [100%]: Average Loss = 169.47
Finished [100%]: Average Loss = 203.04
Finished [100%]: Average Loss = 183.54
Finished [100%]: Average Loss = 170.93
Finished [100%]: Average Loss = 153.08
Finished [100%]: Average Loss = 147.73
Finished [100%]: Average Loss = 120.56
Finished [100%]: Average Loss = 167.9
Finished [100%]: Average Loss = 163.61
Finished [100%]: Average Loss = 195.34
Finished [100%]: Average Loss = 156.36
Finished [100%]: Average Loss = 179.15
Finished [100%]: Average Loss = 164.24
Finished [100%]: Average Loss = 161.97
Finished [100%]: Average Loss = 166.5
Finished [100%]: Average Loss = 163.25
Finished [100%]: Average Loss = 164.43
Finished [100%]: Average Loss = 164.76
Finished [100%]: Average Loss = 176.96
Finished [100%]: Average Loss = 180.77
Finished [100%]: Average Loss = 163.35
Finished [100%]: Average Loss = 163.11
Finished [100%]: Average Loss = 163.45
Finished [100%]: Average Loss = 159.38
Finished [100%]: Average Loss = 172.25
Finished [100%]: Average Loss = 149.93
Finished [100%]: Average Loss = 165.06
Finished [100%]: Average Loss = 172.83
Finished [100%]: Average Loss = 156.3
Finished [100%]: Average Loss = 180
Finished [100%]: Average Loss = 161.31
Finished [100%]: Average Loss = 157.56
Finished [100%]: Average Loss = 158.32
Finished [100%]: Average Loss = 160.93
Finished [100%]: Average Loss = 164.58
Finished [100%]: Average Loss = 181.89
Finished [100%]: Average Loss = 146.47
Finished [100%]: Average Loss = 179.97
Finished [100%]: Average Loss = 158.94
Finished [100%]: Average Loss = 159.03
Finished [100%]: Average Loss = 162.42
Finished [100%]: Average Loss = 162.44
Finished [100%]: Average Loss = 156.41
Finished [100%]: Average Loss = 154.41
Finished [100%]: Average Loss = 137.53
Finished [100%]: Average Loss = 190.89
Finished [100%]: Average Loss = 166.48
Finished [100%]: Average Loss = 137.63
Finished [100%]: Average Loss = 149.52
Finished [100%]: Average Loss = 165.67
Finished [100%]: Average Loss = 162.87
Finished [100%]: Average Loss = 146.86
Finished [100%]: Average Loss = 168.42
Finished [100%]: Average Loss = 167.05
Finished [100%]: Average Loss = 186.6
Finished [100%]: Average Loss = 161.04
Finished [100%]: Average Loss = 162.81
Finished [100%]: Average Loss = 134.16
Finished [100%]: Average Loss = 148.45
Finished [100%]: Average Loss = 146.22
Finished [100%]: Average Loss = 160.45
Finished [100%]: Average Loss = 183.72
Finished [100%]: Average Loss = 160.16
Finished [100%]: Average Loss = 168.35
Finished [100%]: Average Loss = 159.71
Finished [100%]: Average Loss = 160.11
Finished [100%]: Average Loss = 148.24
Finished [100%]: Average Loss = 170.41
Finished [100%]: Average Loss = 183.25
Finished [100%]: Average Loss = 169.95
Finished [100%]: Average Loss = 150.57
Finished [100%]: Average Loss = 186.22
Finished [100%]: Average Loss = 166.54
Finished [100%]: Average Loss = 167.26
Finished [100%]: Average Loss = 142.3
Finished [100%]: Average Loss = 143.5
Finished [100%]: Average Loss = 166.74
Finished [100%]: Average Loss = 158.38
Finished [100%]: Average Loss = 162.37
Finished [100%]: Average Loss = 165.87
Finished [100%]: Average Loss = 143.48
Finished [100%]: Average Loss = 139.3
Finished [100%]: Average Loss = 137.4
Finished [100%]: Average Loss = 142.14
Finished [100%]: Average Loss = 158.3
Finished [100%]: Average Loss = 168.63
Finished [100%]: Average Loss = 160.49
Finished [100%]: Average Loss = 133.6
Finished [100%]: Average Loss = 146.99
Finished [100%]: Average Loss = 165.11
Finished [100%]: Average Loss = 150.24
Finished [100%]: Average Loss = 186.2
Finished [100%]: Average Loss = 148.71
Finished [100%]: Average Loss = 162.17
Finished [100%]: Average Loss = 162.61
Finished [100%]: Average Loss = 143.53
Finished [100%]: Average Loss = 181.48
Finished [100%]: Average Loss = 158.66
Finished [100%]: Average Loss = 135.67
Finished [100%]: Average Loss = 146.72
Finished [100%]: Average Loss = 148.87
Finished [100%]: Average Loss = 144.06
Finished [100%]: Average Loss = 143.53
Finished [100%]: Average Loss = 128.78
Finished [100%]: Average Loss = 158.79
Finished [100%]: Average Loss = 143.09
Finished [100%]: Average Loss = 165.13
Finished [100%]: Average Loss = 152.42
Finished [100%]: Average Loss = 147.48
Finished [100%]: Average Loss = 145.53
Finished [100%]: Average Loss = 168.14
Finished [100%]: Average Loss = 148.89
Finished [100%]: Average Loss = 141.99
Finished [100%]: Average Loss = 125.35
Finished [100%]: Average Loss = 164.51
Finished [100%]: Average Loss = 149.12
Finished [100%]: Average Loss = 149.79
Finished [100%]: Average Loss = 159.97
Finished [100%]: Average Loss = 147.47
Finished [100%]: Average Loss = 160.87
Finished [100%]: Average Loss = 166.13
Finished [100%]: Average Loss = 146.13
Finished [100%]: Average Loss = 221.43
Finished [100%]: Average Loss = 224.37
Finished [100%]: Average Loss = 234.69
Finished [100%]: Average Loss = 213.45
Finished [100%]: Average Loss = 211.85
Finished [100%]: Average Loss = 187.64
Finished [100%]: Average Loss = 187.44
Finished [100%]: Average Loss = 154.4
Finished [100%]: Average Loss = 161.94
Finished [100%]: Average Loss = 165.36
Finished [100%]: Average Loss = 198.54
Finished [100%]: Average Loss = 161.87
Finished [100%]: Average Loss = 219.04
Finished [100%]: Average Loss = 162.09
Finished [100%]: Average Loss = 162.61
Finished [100%]: Average Loss = 155.73
Finished [100%]: Average Loss = 176.23
Finished [100%]: Average Loss = 161.77
Finished [100%]: Average Loss = 184.39
Finished [100%]: Average Loss = 183.61
Finished [100%]: Average Loss = 194.02
Finished [100%]: Average Loss = 181.94
Finished [100%]: Average Loss = 160.99
Finished [100%]: Average Loss = 161.22
Finished [100%]: Average Loss = 156.34
Finished [100%]: Average Loss = 196.3
Finished [100%]: Average Loss = 153.89
Finished [100%]: Average Loss = 166.56
Finished [100%]: Average Loss = 161.94
Finished [100%]: Average Loss = 184.93
Finished [100%]: Average Loss = 184.61
Finished [100%]: Average Loss = 162.73
Finished [100%]: Average Loss = 159.19
Finished [100%]: Average Loss = 164.68
Finished [100%]: Average Loss = 180.7
Finished [100%]: Average Loss = 161.44
Finished [100%]: Average Loss = 151.66
Finished [100%]: Average Loss = 157.26
Finished [100%]: Average Loss = 179.29
Finished [100%]: Average Loss = 180.07
Finished [100%]: Average Loss = 164.15
Finished [100%]: Average Loss = 165.62
Finished [100%]: Average Loss = 167.39
Finished [100%]: Average Loss = 165.37
Finished [100%]: Average Loss = 160.88
Finished [100%]: Average Loss = 180.01
Finished [100%]: Average Loss = 158.81
Finished [100%]: Average Loss = 159.14
Finished [100%]: Average Loss = 158.07
Finished [100%]: Average Loss = 156.42
Finished [100%]: Average Loss = 170.76
Finished [100%]: Average Loss = 176.51
Finished [100%]: Average Loss = 172.71
Finished [100%]: Average Loss = 171.78
Finished [100%]: Average Loss = 170.48
Finished [100%]: Average Loss = 169.96
Finished [100%]: Average Loss = 169.19
Finished [100%]: Average Loss = 167
Finished [100%]: Average Loss = 164.49
Finished [100%]: Average Loss = 166.45
Finished [100%]: Average Loss = 141.12
Finished [100%]: Average Loss = 160.41
Finished [100%]: Average Loss = 176.67
Finished [100%]: Average Loss = 173.73
Finished [100%]: Average Loss = 155.34
Finished [100%]: Average Loss = 160.04
Finished [100%]: Average Loss = 157.58
Finished [100%]: Average Loss = 132.14
Finished [100%]: Average Loss = 133.06
Finished [100%]: Average Loss = 147.93
Finished [100%]: Average Loss = 155.82
Finished [100%]: Average Loss = 168.25
Finished [100%]: Average Loss = 146.17
Finished [100%]: Average Loss = 146.65
Finished [100%]: Average Loss = 165.84
Finished [100%]: Average Loss = 175.2
Finished [100%]: Average Loss = 185.13
Finished [100%]: Average Loss = 159.04
Finished [100%]: Average Loss = 154.62
Finished [100%]: Average Loss = 146.46
Finished [100%]: Average Loss = 136.94
Finished [100%]: Average Loss = 154.84
Finished [100%]: Average Loss = 165.93
Finished [100%]: Average Loss = 169.14
Finished [100%]: Average Loss = 172.19
Finished [100%]: Average Loss = 174.42
Finished [100%]: Average Loss = 127.62
Finished [100%]: Average Loss = 171.31
Finished [100%]: Average Loss = 181.35
Finished [100%]: Average Loss = 158.58

Total time: 1145.9 seconds
Weeks fit: 391
Weeks skipped: 0

In [9]:
weeklyBetaMEDF = pd.DataFrame(weeklyBetaResultsME)
print(weeklyBetaMEDF.shape)
weeklyBetaMEDF.head(13)

(5083, 5)

                     week       region       country  betaMean   betaStd
0   2018-01-01/2018-01-07  Middle East       Bahrain  0.217842  0.101907
1   2018-01-01/2018-01-07  Middle East          Iran  1.165205  0.076633
2   2018-01-01/2018-01-07  Middle East          Iraq -0.020646  0.100990
3   2018-01-01/2018-01-07  Middle East        Israel -1.924097  0.176641
4   2018-01-01/2018-01-07  Middle East        Jordan -1.898124  0.187803
5   2018-01-01/2018-01-07  Middle East        Kuwait  0.581055  0.360420
6   2018-01-01/2018-01-07  Middle East       Lebanon -1.643885  0.161427
7   2018-01-01/2018-01-07  Middle East     Palestine  0.606012  0.094614
8   2018-01-01/2018-01-07  Middle East         Qatar  0.565518  0.371563
9   2018-01-01/2018-01-07  Middle East  Saudi Arabia -0.963435  0.137866
10  2018-01-01/2018-01-07  Middle East         Syria  2.471036  0.078271
11  2018-01-01/2018-01-07  Middle East        Turkey -0.366495  0.119596
12  2018-01-01/2018-01-07  Middle East         Yemen  1.210014  0.173269

In [10]:
weeklyBetaMEDF.to_csv('../Data/Processed/weeklyBetaMiddleEast.csv', index=False)

In [11]:
northAfricaData = countryComparisons[countryComparisons['region'] == 'Northern Africa']
northAfricaCountries = sorted(set(northAfricaData['countryI']) | set(northAfricaData['countryJ']))
northAfricaIndexMap = {country: i for i, country in enumerate(northAfricaCountries)}
nNorthAfricaCountries = len(northAfricaCountries)
northAfricaWeeks = sorted(northAfricaData['week'].unique())

print(nNorthAfricaCountries, len(northAfricaWeeks))

6 391

In [12]:
initialNAWeekData = northAfricaData[northAfricaData['week'] == northAfricaWeeks[0]]

initialNAIndexI = initialNAWeekData['countryI'].map(northAfricaIndexMap).to_numpy()
initialNAIndexJ = initialNAWeekData['countryJ'].map(northAfricaIndexMap).to_numpy()
initialNAWinsI = initialNAWeekData['winsI'].to_numpy()
initialNATotals = initialNAWeekData['total'].to_numpy()

with pm.Model() as northAfricaRollingModel:
    indexIData = pm.Data('indexIData', initialNAIndexI)
    indexJData = pm.Data('indexJData', initialNAIndexJ)
    winsIData = pm.Data('winsIData', initialNAWinsI)
    totalsData = pm.Data('totalsData', initialNATotals)

    beta = pm.ZeroSumNormal('beta', sigma=1.0, shape=nNorthAfricaCountries)
    p = pm.math.sigmoid(beta[indexIData] - beta[indexJData])
    obs = pm.Binomial('obs', n=totalsData, p=p, observed=winsIData)

In [13]:
weeklyBetaResultsNA = []
weeksSkippedNA = []

startTime = time.time()

for week in northAfricaWeeks:
    weekData = northAfricaData[northAfricaData['week'] == week]

    if len(weekData) == 0:
        weeksSkippedNA.append(week)
        continue

    indexI = weekData['countryI'].map(northAfricaIndexMap).to_numpy()
    indexJ = weekData['countryJ'].map(northAfricaIndexMap).to_numpy()
    winsI = weekData['winsI'].to_numpy()
    totals = weekData['total'].to_numpy()

    with northAfricaRollingModel:
        pm.set_data({
            'indexIData': indexI,
            'indexJData': indexJ,
            'winsIData': winsI,
            'totalsData': totals
        })

        approx = pm.fit(n=20000, method='advi', progressbar=False)
        trace = approx.sample(400)

    betaSamples = trace.posterior['beta'].values.reshape(-1, nNorthAfricaCountries)
    betaMeans = betaSamples.mean(axis=0)
    betaStds = betaSamples.std(axis=0)

    for i, country in enumerate(northAfricaCountries):
        weeklyBetaResultsNA.append({
            'week': week,
            'region': 'Northern Africa',
            'country': country,
            'betaMean': betaMeans[i],
            'betaStd': betaStds[i]
        })

endTime = time.time()

print(f"Total time: {endTime - startTime:.1f} seconds")
print(f"Weeks fit: {len(northAfricaWeeks) - len(weeksSkippedNA)}")
print(f"Weeks skipped: {len(weeksSkippedNA)}")

Finished [100%]: Average Loss = 32.238
Finished [100%]: Average Loss = 44.214
Finished [100%]: Average Loss = 38.191
Finished [100%]: Average Loss = 34.996
Finished [100%]: Average Loss = 35.888
Finished [100%]: Average Loss = 31.547
Finished [100%]: Average Loss = 34.73
Finished [100%]: Average Loss = 33.671
Finished [100%]: Average Loss = 32.441
Finished [100%]: Average Loss = 34.471
Finished [100%]: Average Loss = 33.043
Finished [100%]: Average Loss = 32.531
Finished [100%]: Average Loss = 23.199
Finished [100%]: Average Loss = 16.63
Finished [100%]: Average Loss = 29.66
Finished [100%]: Average Loss = 30.986
Finished [100%]: Average Loss = 32.293
Finished [100%]: Average Loss = 28.31
Finished [100%]: Average Loss = 29.241
Finished [100%]: Average Loss = 32.34
Finished [100%]: Average Loss = 34.133
Finished [100%]: Average Loss = 25.951
Finished [100%]: Average Loss = 31.766
Finished [100%]: Average Loss = 23.55
Finished [100%]: Average Loss = 28.863
Finished [100%]: Average Loss = 31.911
Finished [100%]: Average Loss = 27.534
Finished [100%]: Average Loss = 30.824
Finished [100%]: Average Loss = 21.773
Finished [100%]: Average Loss = 30.617
Finished [100%]: Average Loss = 22.697
Finished [100%]: Average Loss = 18.2
Finished [100%]: Average Loss = 29.261
Finished [100%]: Average Loss = 24.728
Finished [100%]: Average Loss = 33.763
Finished [100%]: Average Loss = 35.145
Finished [100%]: Average Loss = 20.126
Finished [100%]: Average Loss = 24.681
Finished [100%]: Average Loss = 32.389
Finished [100%]: Average Loss = 22.114
Finished [100%]: Average Loss = 30.551
Finished [100%]: Average Loss = 32.673
Finished [100%]: Average Loss = 36.399
Finished [100%]: Average Loss = 25.219
Finished [100%]: Average Loss = 37.578
Finished [100%]: Average Loss = 40.528
Finished [100%]: Average Loss = 38.62
Finished [100%]: Average Loss = 40.929
Finished [100%]: Average Loss = 43.349
Finished [100%]: Average Loss = 42.147
Finished [100%]: Average Loss = 43.329
Finished [100%]: Average Loss = 43.119
Finished [100%]: Average Loss = 41.144
Finished [100%]: Average Loss = 41.315
Finished [100%]: Average Loss = 44.546
Finished [100%]: Average Loss = 42.804
Finished [100%]: Average Loss = 39.234
Finished [100%]: Average Loss = 41.315
Finished [100%]: Average Loss = 39.867
Finished [100%]: Average Loss = 45.334
Finished [100%]: Average Loss = 45.303
Finished [100%]: Average Loss = 44.453
Finished [100%]: Average Loss = 44.096
Finished [100%]: Average Loss = 43.49
Finished [100%]: Average Loss = 43.668
Finished [100%]: Average Loss = 43.058
Finished [100%]: Average Loss = 46.051
Finished [100%]: Average Loss = 44.128
Finished [100%]: Average Loss = 47.354
Finished [100%]: Average Loss = 44.328
Finished [100%]: Average Loss = 41.448
Finished [100%]: Average Loss = 42.58
Finished [100%]: Average Loss = 43.786
Finished [100%]: Average Loss = 43.066
Finished [100%]: Average Loss = 39.665
Finished [100%]: Average Loss = 40.886
Finished [100%]: Average Loss = 41.619
Finished [100%]: Average Loss = 39.84
Finished [100%]: Average Loss = 41.675
Finished [100%]: Average Loss = 42.643
Finished [100%]: Average Loss = 43.746
Finished [100%]: Average Loss = 42.542
Finished [100%]: Average Loss = 39.52
Finished [100%]: Average Loss = 39.466
Finished [100%]: Average Loss = 39.17
Finished [100%]: Average Loss = 41.77
Finished [100%]: Average Loss = 42.841
Finished [100%]: Average Loss = 40.846
Finished [100%]: Average Loss = 41.703
Finished [100%]: Average Loss = 43.761
Finished [100%]: Average Loss = 45.835
Finished [100%]: Average Loss = 42.477
Finished [100%]: Average Loss = 38.329
Finished [100%]: Average Loss = 41.963
Finished [100%]: Average Loss = 44.647
Finished [100%]: Average Loss = 42.875
Finished [100%]: Average Loss = 40.991
Finished [100%]: Average Loss = 44.014
Finished [100%]: Average Loss = 40.634
Finished [100%]: Average Loss = 43.775
Finished [100%]: Average Loss = 42.83
Finished [100%]: Average Loss = 44.327
Finished [100%]: Average Loss = 42.118
Finished [100%]: Average Loss = 38.985
Finished [100%]: Average Loss = 41.41
Finished [100%]: Average Loss = 39.786
Finished [100%]: Average Loss = 40.525
Finished [100%]: Average Loss = 40.184
Finished [100%]: Average Loss = 44.732
Finished [100%]: Average Loss = 43.335
Finished [100%]: Average Loss = 44.538
Finished [100%]: Average Loss = 43.54
Finished [100%]: Average Loss = 44.259
Finished [100%]: Average Loss = 45.438
Finished [100%]: Average Loss = 43.32
Finished [100%]: Average Loss = 37.896
Finished [100%]: Average Loss = 37.484
Finished [100%]: Average Loss = 36.611
Finished [100%]: Average Loss = 36.317
Finished [100%]: Average Loss = 40.708
Finished [100%]: Average Loss = 40.927
Finished [100%]: Average Loss = 39.515
Finished [100%]: Average Loss = 42.425
Finished [100%]: Average Loss = 43.926
Finished [100%]: Average Loss = 42.694
Finished [100%]: Average Loss = 42.742
Finished [100%]: Average Loss = 44.283
Finished [100%]: Average Loss = 43.368
Finished [100%]: Average Loss = 41.922
Finished [100%]: Average Loss = 41.658
Finished [100%]: Average Loss = 41.761
Finished [100%]: Average Loss = 44.591
Finished [100%]: Average Loss = 41.415
Finished [100%]: Average Loss = 42.751
Finished [100%]: Average Loss = 40.013
Finished [100%]: Average Loss = 40.553
Finished [100%]: Average Loss = 40.512
Finished [100%]: Average Loss = 44.225
Finished [100%]: Average Loss = 44.916
Finished [100%]: Average Loss = 39.655
Finished [100%]: Average Loss = 42.528
Finished [100%]: Average Loss = 39.907
Finished [100%]: Average Loss = 47.152
Finished [100%]: Average Loss = 42.064
Finished [100%]: Average Loss = 45.096
Finished [100%]: Average Loss = 42.131
Finished [100%]: Average Loss = 43.451
Finished [100%]: Average Loss = 40.948
Finished [100%]: Average Loss = 41.236
Finished [100%]: Average Loss = 41.272
Finished [100%]: Average Loss = 29.687
Finished [100%]: Average Loss = 40.591
Finished [100%]: Average Loss = 41.519
Finished [100%]: Average Loss = 43.663
Finished [100%]: Average Loss = 42.985
Finished [100%]: Average Loss = 38.72
Finished [100%]: Average Loss = 40.205
Finished [100%]: Average Loss = 39.162
Finished [100%]: Average Loss = 32.155
Finished [100%]: Average Loss = 44.944
Finished [100%]: Average Loss = 41.873
Finished [100%]: Average Loss = 41.775
Finished [100%]: Average Loss = 32.679
Finished [100%]: Average Loss = 38.535
Finished [100%]: Average Loss = 41.085
Finished [100%]: Average Loss = 31.14
Finished [100%]: Average Loss = 29.001
Finished [100%]: Average Loss = 39.868
Finished [100%]: Average Loss = 41.71
Finished [100%]: Average Loss = 38.261
Finished [100%]: Average Loss = 45.005
Finished [100%]: Average Loss = 38.28
Finished [100%]: Average Loss = 38.024
Finished [100%]: Average Loss = 31.925
Finished [100%]: Average Loss = 29.898
Finished [100%]: Average Loss = 40.317
Finished [100%]: Average Loss = 43.627
Finished [100%]: Average Loss = 38.949
Finished [100%]: Average Loss = 37.441
Finished [100%]: Average Loss = 39.578
Finished [100%]: Average Loss = 41.056
Finished [100%]: Average Loss = 36.519
Finished [100%]: Average Loss = 37.804
Finished [100%]: Average Loss = 38.678
Finished [100%]: Average Loss = 40.972
Finished [100%]: Average Loss = 32.919
Finished [100%]: Average Loss = 40.2
Finished [100%]: Average Loss = 39.094
Finished [100%]: Average Loss = 35.78
Finished [100%]: Average Loss = 34.481
Finished [100%]: Average Loss = 37.014
Finished [100%]: Average Loss = 36.742
Finished [100%]: Average Loss = 38.755
Finished [100%]: Average Loss = 39.433
Finished [100%]: Average Loss = 36.556
Finished [100%]: Average Loss = 36.462
Finished [100%]: Average Loss = 37.96
Finished [100%]: Average Loss = 37.141
Finished [100%]: Average Loss = 29.676
Finished [100%]: Average Loss = 38.896
Finished [100%]: Average Loss = 40.05
Finished [100%]: Average Loss = 37.739
Finished [100%]: Average Loss = 40.334
Finished [100%]: Average Loss = 42.832
Finished [100%]: Average Loss = 41.586
Finished [100%]: Average Loss = 39.144
Finished [100%]: Average Loss = 41.26
Finished [100%]: Average Loss = 39.441
Finished [100%]: Average Loss = 40.618
Finished [100%]: Average Loss = 39.525
Finished [100%]: Average Loss = 38.78
Finished [100%]: Average Loss = 37.92
Finished [100%]: Average Loss = 39.049
Finished [100%]: Average Loss = 35.585
Finished [100%]: Average Loss = 37.186
Finished [100%]: Average Loss = 40.106
Finished [100%]: Average Loss = 41.288
Finished [100%]: Average Loss = 40.536
Finished [100%]: Average Loss = 40.727
Finished [100%]: Average Loss = 38.513
Finished [100%]: Average Loss = 40.248
Finished [100%]: Average Loss = 39.876
Finished [100%]: Average Loss = 37.988
Finished [100%]: Average Loss = 27.007
Finished [100%]: Average Loss = 40.34
Finished [100%]: Average Loss = 36.455
Finished [100%]: Average Loss = 25.696
Finished [100%]: Average Loss = 38.715
Finished [100%]: Average Loss = 29.048
Finished [100%]: Average Loss = 34.487
Finished [100%]: Average Loss = 37.463
Finished [100%]: Average Loss = 37.473
Finished [100%]: Average Loss = 35.08
Finished [100%]: Average Loss = 38.035
Finished [100%]: Average Loss = 40.508
Finished [100%]: Average Loss = 37.244
Finished [100%]: Average Loss = 29.868
Finished [100%]: Average Loss = 33.902
Finished [100%]: Average Loss = 33.456
Finished [100%]: Average Loss = 33.499
Finished [100%]: Average Loss = 36.083
Finished [100%]: Average Loss = 33.49
Finished [100%]: Average Loss = 32.865
Finished [100%]: Average Loss = 33.676
Finished [100%]: Average Loss = 36.017
Finished [100%]: Average Loss = 34.11
Finished [100%]: Average Loss = 38.222
Finished [100%]: Average Loss = 35.901
Finished [100%]: Average Loss = 34.735
Finished [100%]: Average Loss = 36.552
Finished [100%]: Average Loss = 30.127
Finished [100%]: Average Loss = 35.608
Finished [100%]: Average Loss = 36.686
Finished [100%]: Average Loss = 38.833
Finished [100%]: Average Loss = 36.105
Finished [100%]: Average Loss = 32.933
Finished [100%]: Average Loss = 26.852
Finished [100%]: Average Loss = 34.635
Finished [100%]: Average Loss = 26.498
Finished [100%]: Average Loss = 31.373
Finished [100%]: Average Loss = 38.114
Finished [100%]: Average Loss = 34.521
Finished [100%]: Average Loss = 27.741
Finished [100%]: Average Loss = 27.526
Finished [100%]: Average Loss = 26.766
Finished [100%]: Average Loss = 36.8
Finished [100%]: Average Loss = 36.834
Finished [100%]: Average Loss = 28.004
Finished [100%]: Average Loss = 30.251
Finished [100%]: Average Loss = 37.499
Finished [100%]: Average Loss = 35.237
Finished [100%]: Average Loss = 25.297
Finished [100%]: Average Loss = 30.714
Finished [100%]: Average Loss = 35.007
Finished [100%]: Average Loss = 25.052
Finished [100%]: Average Loss = 31.116
Finished [100%]: Average Loss = 20.039
Finished [100%]: Average Loss = 29.027
Finished [100%]: Average Loss = 31.207
Finished [100%]: Average Loss = 37.104
Finished [100%]: Average Loss = 30.85
Finished [100%]: Average Loss = 37.368
Finished [100%]: Average Loss = 29.053
Finished [100%]: Average Loss = 27.089
Finished [100%]: Average Loss = 33.294
Finished [100%]: Average Loss = 36.732
Finished [100%]: Average Loss = 23.956
Finished [100%]: Average Loss = 35.57
Finished [100%]: Average Loss = 37.521
Finished [100%]: Average Loss = 29.174
Finished [100%]: Average Loss = 39.748
Finished [100%]: Average Loss = 39.287
Finished [100%]: Average Loss = 37.631
Finished [100%]: Average Loss = 29.978
Finished [100%]: Average Loss = 39.835
Finished [100%]: Average Loss = 40.46
Finished [100%]: Average Loss = 30.139
Finished [100%]: Average Loss = 19.711
Finished [100%]: Average Loss = 35.24
Finished [100%]: Average Loss = 28.335
Finished [100%]: Average Loss = 40.361
Finished [100%]: Average Loss = 47.245
Finished [100%]: Average Loss = 54.159
Finished [100%]: Average Loss = 45.671
Finished [100%]: Average Loss = 41.361
Finished [100%]: Average Loss = 40.745
Finished [100%]: Average Loss = 41.296
Finished [100%]: Average Loss = 41.164
Finished [100%]: Average Loss = 31.473
Finished [100%]: Average Loss = 32.023
Finished [100%]: Average Loss = 39.808
Finished [100%]: Average Loss = 39.208
Finished [100%]: Average Loss = 39.613
Finished [100%]: Average Loss = 32.323
Finished [100%]: Average Loss = 42.402
Finished [100%]: Average Loss = 43.046
Finished [100%]: Average Loss = 22.326
Finished [100%]: Average Loss = 42.654
Finished [100%]: Average Loss = 41.218
Finished [100%]: Average Loss = 32.886
Finished [100%]: Average Loss = 42.114
Finished [100%]: Average Loss = 41.794
Finished [100%]: Average Loss = 42.599
Finished [100%]: Average Loss = 39.809
Finished [100%]: Average Loss = 39.47
Finished [100%]: Average Loss = 35.504
Finished [100%]: Average Loss = 44.651
Finished [100%]: Average Loss = 38.48
Finished [100%]: Average Loss = 41.602
Finished [100%]: Average Loss = 42.959
Finished [100%]: Average Loss = 42.032
Finished [100%]: Average Loss = 40.968
Finished [100%]: Average Loss = 42.651
Finished [100%]: Average Loss = 39.377
Finished [100%]: Average Loss = 41.229
Finished [100%]: Average Loss = 41.655
Finished [100%]: Average Loss = 40.434
Finished [100%]: Average Loss = 37.354
Finished [100%]: Average Loss = 39.246
Finished [100%]: Average Loss = 39.003
Finished [100%]: Average Loss = 30.174
Finished [100%]: Average Loss = 40.161
Finished [100%]: Average Loss = 39.826
Finished [100%]: Average Loss = 29.928
Finished [100%]: Average Loss = 40.546
Finished [100%]: Average Loss = 31.761
Finished [100%]: Average Loss = 39.378
Finished [100%]: Average Loss = 31.279
Finished [100%]: Average Loss = 42.286
Finished [100%]: Average Loss = 40.313
Finished [100%]: Average Loss = 39.275
Finished [100%]: Average Loss = 41.599
Finished [100%]: Average Loss = 41.472
Finished [100%]: Average Loss = 41.609
Finished [100%]: Average Loss = 41.946
Finished [100%]: Average Loss = 43.625
Finished [100%]: Average Loss = 39.369
Finished [100%]: Average Loss = 41.301
Finished [100%]: Average Loss = 31.499
Finished [100%]: Average Loss = 41.165
Finished [100%]: Average Loss = 32.088
Finished [100%]: Average Loss = 39.594
Finished [100%]: Average Loss = 37.378
Finished [100%]: Average Loss = 21.633
Finished [100%]: Average Loss = 39.083
Finished [100%]: Average Loss = 39.19
Finished [100%]: Average Loss = 42.501
Finished [100%]: Average Loss = 42.762
Finished [100%]: Average Loss = 43.806
Finished [100%]: Average Loss = 39.003
Finished [100%]: Average Loss = 37.746
Finished [100%]: Average Loss = 42.803
Finished [100%]: Average Loss = 41.929
Finished [100%]: Average Loss = 38.244
Finished [100%]: Average Loss = 35.64
Finished [100%]: Average Loss = 28.894
Finished [100%]: Average Loss = 41.901
Finished [100%]: Average Loss = 40.006
Finished [100%]: Average Loss = 43.901
Finished [100%]: Average Loss = 45.718
Finished [100%]: Average Loss = 41.85
Finished [100%]: Average Loss = 32.254
Finished [100%]: Average Loss = 42.805
Finished [100%]: Average Loss = 40.001
Finished [100%]: Average Loss = 45.004
Finished [100%]: Average Loss = 41.54
Finished [100%]: Average Loss = 42.043
Finished [100%]: Average Loss = 28.805
Finished [100%]: Average Loss = 39.693
Finished [100%]: Average Loss = 42.153
Finished [100%]: Average Loss = 25.424

Total time: 990.3 seconds
Weeks fit: 391
Weeks skipped: 0

In [14]:
weeklyBetaNADF = pd.DataFrame(weeklyBetaResultsNA)
print(weeklyBetaNADF.shape)
weeklyBetaNADF.head(6)

(2346, 5)

                    week           region  country  betaMean   betaStd
0  2018-01-01/2018-01-07  Northern Africa  Algeria  0.257720  0.212217
1  2018-01-01/2018-01-07  Northern Africa    Egypt  0.288021  0.207301
2  2018-01-01/2018-01-07  Northern Africa    Libya  0.270538  0.186070
3  2018-01-01/2018-01-07  Northern Africa  Morocco -0.411485  0.230841
4  2018-01-01/2018-01-07  Northern Africa    Sudan  0.804794  0.184471
5  2018-01-01/2018-01-07  Northern Africa  Tunisia -1.209588  0.199556

In [15]:
weeklyBetaNADF.to_csv('../Data/Processed/weeklyBetaNorthAfrica.csv', index=False)

In [3]:
europeData = countryComparisons[countryComparisons['region'] == 'Europe']
europeCountries = sorted(set(europeData['countryI']) | set(europeData['countryJ']))
europeIndexMap = {country: i for i, country in enumerate(europeCountries)}
nEuropeCountries = len(europeCountries)
europeWeeks = sorted(europeData['week'].unique())

print(nEuropeCountries, len(europeWeeks))

41 391

In [4]:
initialEuWeekData = europeData[europeData['week'] == europeWeeks[0]]

initialEuIndexI = initialEuWeekData['countryI'].map(europeIndexMap).to_numpy()
initialEuIndexJ = initialEuWeekData['countryJ'].map(europeIndexMap).to_numpy()
initialEuWinsI = initialEuWeekData['winsI'].to_numpy()
initialEuTotals = initialEuWeekData['total'].to_numpy()

with pm.Model() as europeRollingModel:
    indexIData = pm.Data('indexIData', initialEuIndexI)
    indexJData = pm.Data('indexJData', initialEuIndexJ)
    winsIData = pm.Data('winsIData', initialEuWinsI)
    totalsData = pm.Data('totalsData', initialEuTotals)

    beta = pm.ZeroSumNormal('beta', sigma=1.0, shape=nEuropeCountries)
    p = pm.math.sigmoid(beta[indexIData] - beta[indexJData])
    obs = pm.Binomial('obs', n=totalsData, p=p, observed=winsIData)

In [5]:
weeklyBetaResultsEurope = []
weeksSkippedEurope = []

startTime = time.time()

for week in europeWeeks:
    weekData = europeData[europeData['week'] == week]

    if len(weekData) == 0:
        weeksSkippedEurope.append(week)
        continue

    indexI = weekData['countryI'].map(europeIndexMap).to_numpy()
    indexJ = weekData['countryJ'].map(europeIndexMap).to_numpy()
    winsI = weekData['winsI'].to_numpy()
    totals = weekData['total'].to_numpy()

    with europeRollingModel:
        pm.set_data({
            'indexIData': indexI,
            'indexJData': indexJ,
            'winsIData': winsI,
            'totalsData': totals
        })

        approx = pm.fit(n=20000, method='advi', progressbar=False)
        trace = approx.sample(400)

    betaSamples = trace.posterior['beta'].values.reshape(-1, nEuropeCountries)
    betaMeans = betaSamples.mean(axis=0)
    betaStds = betaSamples.std(axis=0)

    for i, country in enumerate(europeCountries):
        weeklyBetaResultsEurope.append({
            'week': week,
            'region': 'Europe',
            'country': country,
            'betaMean': betaMeans[i],
            'betaStd': betaStds[i]
        })

endTime = time.time()

print(f"Total time: {endTime - startTime:.1f} seconds")
print(f"Weeks fit: {len(europeWeeks) - len(weeksSkippedEurope)}")
print(f"Weeks skipped: {len(weeksSkippedEurope)}")

Finished [100%]: Average Loss = 48.08
Finished [100%]: Average Loss = 100.17
Finished [100%]: Average Loss = 144.45
Finished [100%]: Average Loss = 134.46
Finished [100%]: Average Loss = 163.07
Finished [100%]: Average Loss = 151.26
Finished [100%]: Average Loss = 156.66
Finished [100%]: Average Loss = 164.41
Finished [100%]: Average Loss = 179
Finished [100%]: Average Loss = 177.06
Finished [100%]: Average Loss = 145.52
Finished [100%]: Average Loss = 138.04
Finished [100%]: Average Loss = 142.28
Finished [100%]: Average Loss = 168.7
Finished [100%]: Average Loss = 104.94
Finished [100%]: Average Loss = 154.79
Finished [100%]: Average Loss = 159.63
Finished [100%]: Average Loss = 147.46
Finished [100%]: Average Loss = 137.71
Finished [100%]: Average Loss = 158.55
Finished [100%]: Average Loss = 159.19
Finished [100%]: Average Loss = 132
Finished [100%]: Average Loss = 199.96
Finished [100%]: Average Loss = 198.23
Finished [100%]: Average Loss = 196.11
Finished [100%]: Average Loss = 165.4
Finished [100%]: Average Loss = 165.47
Finished [100%]: Average Loss = 148.05
Finished [100%]: Average Loss = 146.73
Finished [100%]: Average Loss = 150.38
Finished [100%]: Average Loss = 82.569
Finished [100%]: Average Loss = 94.875
Finished [100%]: Average Loss = 127.97
Finished [100%]: Average Loss = 122.03
Finished [100%]: Average Loss = 145.3
Finished [100%]: Average Loss = 181.42
Finished [100%]: Average Loss = 163.85
Finished [100%]: Average Loss = 171.02
Finished [100%]: Average Loss = 172.66
Finished [100%]: Average Loss = 192.73
Finished [100%]: Average Loss = 139.76
Finished [100%]: Average Loss = 158.14
Finished [100%]: Average Loss = 154.73
Finished [100%]: Average Loss = 187.23
Finished [100%]: Average Loss = 165.02
Finished [100%]: Average Loss = 187.11
Finished [100%]: Average Loss = 166.01
Finished [100%]: Average Loss = 186.4
Finished [100%]: Average Loss = 186.95
Finished [100%]: Average Loss = 179.65
Finished [100%]: Average Loss = 181.3
Finished [100%]: Average Loss = 166.08
Finished [100%]: Average Loss = 83.885
Finished [100%]: Average Loss = 140.33
Finished [100%]: Average Loss = 178.19
Finished [100%]: Average Loss = 160.22
Finished [100%]: Average Loss = 180.96
Finished [100%]: Average Loss = 172.59
Finished [100%]: Average Loss = 208.16
Finished [100%]: Average Loss = 178.57
Finished [100%]: Average Loss = 186.99
Finished [100%]: Average Loss = 216.81
Finished [100%]: Average Loss = 211.43
Finished [100%]: Average Loss = 210.27
Finished [100%]: Average Loss = 208.68
Finished [100%]: Average Loss = 202.69
Finished [100%]: Average Loss = 208.15
Finished [100%]: Average Loss = 183.52
Finished [100%]: Average Loss = 202.4
Finished [100%]: Average Loss = 189.02
Finished [100%]: Average Loss = 191.63
Finished [100%]: Average Loss = 174.88
Finished [100%]: Average Loss = 194.45
Finished [100%]: Average Loss = 182.67
Finished [100%]: Average Loss = 197.81
Finished [100%]: Average Loss = 149.34
Finished [100%]: Average Loss = 188.87
Finished [100%]: Average Loss = 183.94
Finished [100%]: Average Loss = 202.18
Finished [100%]: Average Loss = 196.01
Finished [100%]: Average Loss = 189.15
Finished [100%]: Average Loss = 183.78
Finished [100%]: Average Loss = 176.72
Finished [100%]: Average Loss = 121.5
Finished [100%]: Average Loss = 174.52
Finished [100%]: Average Loss = 154.55
Finished [100%]: Average Loss = 180.95
Finished [100%]: Average Loss = 162.19
Finished [100%]: Average Loss = 161.26
Finished [100%]: Average Loss = 208.3
Finished [100%]: Average Loss = 180.04
Finished [100%]: Average Loss = 199.08
Finished [100%]: Average Loss = 198.43
Finished [100%]: Average Loss = 193.86
Finished [100%]: Average Loss = 202.57
Finished [100%]: Average Loss = 193.12
Finished [100%]: Average Loss = 209.68
Finished [100%]: Average Loss = 201.81
Finished [100%]: Average Loss = 176.07
Finished [100%]: Average Loss = 180.62
Finished [100%]: Average Loss = 158.43
Finished [100%]: Average Loss = 187.85
Finished [100%]: Average Loss = 210.27
Finished [100%]: Average Loss = 173.82
Finished [100%]: Average Loss = 500.87
Finished [100%]: Average Loss = 899.65
Finished [100%]: Average Loss = 1,250.8
Finished [100%]: Average Loss = 1,044.4
Finished [100%]: Average Loss = 1,317.6
Finished [100%]: Average Loss = 1,167.8
Finished [100%]: Average Loss = 1,036.2
Finished [100%]: Average Loss = 1,249.5
Finished [100%]: Average Loss = 1,169.3
Finished [100%]: Average Loss = 921.44
Finished [100%]: Average Loss = 1,358.8
Finished [100%]: Average Loss = 605.21
Finished [100%]: Average Loss = 448.03
Finished [100%]: Average Loss = 361.45
Finished [100%]: Average Loss = 327.84
Finished [100%]: Average Loss = 652.13
Finished [100%]: Average Loss = 596.67
Finished [100%]: Average Loss = 970.26
Finished [100%]: Average Loss = 868.98
Finished [100%]: Average Loss = 1,024.9
Finished [100%]: Average Loss = 1,072.7
Finished [100%]: Average Loss = 1,164.1
Finished [100%]: Average Loss = 1,147.7
Finished [100%]: Average Loss = 1,327.3
Finished [100%]: Average Loss = 1,329.3
Finished [100%]: Average Loss = 1,208.3
Finished [100%]: Average Loss = 1,193.2
Finished [100%]: Average Loss = 1,156.3
Finished [100%]: Average Loss = 1,015.2
Finished [100%]: Average Loss = 1,148.7
Finished [100%]: Average Loss = 1,010.3
Finished [100%]: Average Loss = 912.38
Finished [100%]: Average Loss = 1,205.6
Finished [100%]: Average Loss = 1,027.4
Finished [100%]: Average Loss = 980.7
Finished [100%]: Average Loss = 1,212.7
Finished [100%]: Average Loss = 1,213.8
Finished [100%]: Average Loss = 1,333.3
Finished [100%]: Average Loss = 1,415.6
Finished [100%]: Average Loss = 1,283.5
Finished [100%]: Average Loss = 1,408.5
Finished [100%]: Average Loss = 1,241
Finished [100%]: Average Loss = 1,200.4
Finished [100%]: Average Loss = 1,270.1
Finished [100%]: Average Loss = 1,201.2
Finished [100%]: Average Loss = 1,061.8
Finished [100%]: Average Loss = 1,118.7
Finished [100%]: Average Loss = 971.3
Finished [100%]: Average Loss = 1,183.4
Finished [100%]: Average Loss = 1,114.6
Finished [100%]: Average Loss = 1,117.1
Finished [100%]: Average Loss = 893.88
Finished [100%]: Average Loss = 731.74
Finished [100%]: Average Loss = 780.25
Finished [100%]: Average Loss = 935.94
Finished [100%]: Average Loss = 994.47
Finished [100%]: Average Loss = 1,139.5
Finished [100%]: Average Loss = 1,196.8
Finished [100%]: Average Loss = 1,097.1
Finished [100%]: Average Loss = 1,101.8
Finished [100%]: Average Loss = 1,219.7
Finished [100%]: Average Loss = 1,194
Finished [100%]: Average Loss = 1,189.6
Finished [100%]: Average Loss = 1,301.7
Finished [100%]: Average Loss = 1,202.5
Finished [100%]: Average Loss = 1,259.6
Finished [100%]: Average Loss = 1,240.5
Finished [100%]: Average Loss = 1,175
Finished [100%]: Average Loss = 1,279.8
Finished [100%]: Average Loss = 1,173.1
Finished [100%]: Average Loss = 1,173.9
Finished [100%]: Average Loss = 1,126.9
Finished [100%]: Average Loss = 1,272.5
Finished [100%]: Average Loss = 1,386.9
Finished [100%]: Average Loss = 1,298.7
Finished [100%]: Average Loss = 1,256.9
Finished [100%]: Average Loss = 1,251.3
Finished [100%]: Average Loss = 1,163.3
Finished [100%]: Average Loss = 1,200.6
Finished [100%]: Average Loss = 1,029.7
Finished [100%]: Average Loss = 1,177.5
Finished [100%]: Average Loss = 1,073.8
Finished [100%]: Average Loss = 1,008.7
Finished [100%]: Average Loss = 1,048.4
Finished [100%]: Average Loss = 1,099.3
Finished [100%]: Average Loss = 1,025.3
Finished [100%]: Average Loss = 956.23
Finished [100%]: Average Loss = 1,004
Finished [100%]: Average Loss = 1,161
Finished [100%]: Average Loss = 1,190.9
Finished [100%]: Average Loss = 1,338.5
Finished [100%]: Average Loss = 1,234.3
Finished [100%]: Average Loss = 1,276.4
Finished [100%]: Average Loss = 1,167.3
Finished [100%]: Average Loss = 1,206.8
Finished [100%]: Average Loss = 1,255.5
Finished [100%]: Average Loss = 1,050.5
Finished [100%]: Average Loss = 1,287.9
Finished [100%]: Average Loss = 1,285.8
Finished [100%]: Average Loss = 1,281.5
Finished [100%]: Average Loss = 1,156.3
Finished [100%]: Average Loss = 1,133.5
Finished [100%]: Average Loss = 1,216.2
Finished [100%]: Average Loss = 1,076.7
Finished [100%]: Average Loss = 804.43
Finished [100%]: Average Loss = 663.61
Finished [100%]: Average Loss = 1,006.4
Finished [100%]: Average Loss = 1,177
Finished [100%]: Average Loss = 1,070.9
Finished [100%]: Average Loss = 1,062.7
Finished [100%]: Average Loss = 1,156.9
Finished [100%]: Average Loss = 1,345.2
Finished [100%]: Average Loss = 1,513
Finished [100%]: Average Loss = 1,533.9
Finished [100%]: Average Loss = 1,356.6
Finished [100%]: Average Loss = 1,309.4
Finished [100%]: Average Loss = 1,310.2
Finished [100%]: Average Loss = 1,312.4
Finished [100%]: Average Loss = 1,296
Finished [100%]: Average Loss = 1,157
Finished [100%]: Average Loss = 1,332.5
Finished [100%]: Average Loss = 1,086
Finished [100%]: Average Loss = 1,275.1
Finished [100%]: Average Loss = 1,200.7
Finished [100%]: Average Loss = 1,141.9
Finished [100%]: Average Loss = 1,252.6
Finished [100%]: Average Loss = 1,130.1
Finished [100%]: Average Loss = 1,143.7
Finished [100%]: Average Loss = 1,290.4
Finished [100%]: Average Loss = 1,050.6
Finished [100%]: Average Loss = 1,067.5
Finished [100%]: Average Loss = 988
Finished [100%]: Average Loss = 906.07
Finished [100%]: Average Loss = 739.15
Finished [100%]: Average Loss = 1,059.8
Finished [100%]: Average Loss = 877.77
Finished [100%]: Average Loss = 867.52
Finished [100%]: Average Loss = 766.97
Finished [100%]: Average Loss = 902.19
Finished [100%]: Average Loss = 648.23
Finished [100%]: Average Loss = 984.79
Finished [100%]: Average Loss = 1,066.9
Finished [100%]: Average Loss = 1,108.7
Finished [100%]: Average Loss = 1,199.9
Finished [100%]: Average Loss = 1,186.2
Finished [100%]: Average Loss = 1,214.9
Finished [100%]: Average Loss = 1,152.7
Finished [100%]: Average Loss = 1,276.5
Finished [100%]: Average Loss = 1,131.3
Finished [100%]: Average Loss = 1,007.6
Finished [100%]: Average Loss = 1,264
Finished [100%]: Average Loss = 1,135.3
Finished [100%]: Average Loss = 1,127.6
Finished [100%]: Average Loss = 1,119.1
Finished [100%]: Average Loss = 1,147.4
Finished [100%]: Average Loss = 843.39
Finished [100%]: Average Loss = 497
Finished [100%]: Average Loss = 674.64
Finished [100%]: Average Loss = 951.08
Finished [100%]: Average Loss = 1,006.1
Finished [100%]: Average Loss = 1,108.9
Finished [100%]: Average Loss = 845.38
Finished [100%]: Average Loss = 1,161.9
Finished [100%]: Average Loss = 1,057.6
Finished [100%]: Average Loss = 1,352.7
Finished [100%]: Average Loss = 1,272.9
Finished [100%]: Average Loss = 1,324
Finished [100%]: Average Loss = 1,275.8
Finished [100%]: Average Loss = 1,312.5
Finished [100%]: Average Loss = 1,079.8
Finished [100%]: Average Loss = 992.7
Finished [100%]: Average Loss = 923.66
Finished [100%]: Average Loss = 1,040.5
Finished [100%]: Average Loss = 1,085.2
Finished [100%]: Average Loss = 1,198.8
Finished [100%]: Average Loss = 1,051
Finished [100%]: Average Loss = 1,223.7
Finished [100%]: Average Loss = 1,158
Finished [100%]: Average Loss = 1,160.8
Finished [100%]: Average Loss = 1,191
Finished [100%]: Average Loss = 1,101.9
Finished [100%]: Average Loss = 1,091.7
Finished [100%]: Average Loss = 1,056
Finished [100%]: Average Loss = 906.3
Finished [100%]: Average Loss = 982.2
Finished [100%]: Average Loss = 1,035.9
Finished [100%]: Average Loss = 990.17
Finished [100%]: Average Loss = 900.57
Finished [100%]: Average Loss = 865.56
Finished [100%]: Average Loss = 802.12
Finished [100%]: Average Loss = 959.62
Finished [100%]: Average Loss = 1,067.6
Finished [100%]: Average Loss = 1,098.8
Finished [100%]: Average Loss = 1,186.6
Finished [100%]: Average Loss = 1,124.9
Finished [100%]: Average Loss = 1,111
Finished [100%]: Average Loss = 1,128.5
Finished [100%]: Average Loss = 1,227.8
Finished [100%]: Average Loss = 1,312
Finished [100%]: Average Loss = 1,304.8
Finished [100%]: Average Loss = 1,161.6
Finished [100%]: Average Loss = 1,145.4
Finished [100%]: Average Loss = 1,155.4
Finished [100%]: Average Loss = 1,317.5
Finished [100%]: Average Loss = 1,139.1
Finished [100%]: Average Loss = 1,012.9
Finished [100%]: Average Loss = 1,201.4
Finished [100%]: Average Loss = 1,077.9
Finished [100%]: Average Loss = 671.03
Finished [100%]: Average Loss = 770.07
Finished [100%]: Average Loss = 1,115.2
Finished [100%]: Average Loss = 1,119.4
Finished [100%]: Average Loss = 1,320.2
Finished [100%]: Average Loss = 1,346.2
Finished [100%]: Average Loss = 1,361.2
Finished [100%]: Average Loss = 1,239.6
Finished [100%]: Average Loss = 1,231.2
Finished [100%]: Average Loss = 1,458.3
Finished [100%]: Average Loss = 1,357.6
Finished [100%]: Average Loss = 1,070.5
Finished [100%]: Average Loss = 1,184.5
Finished [100%]: Average Loss = 1,080.4
Finished [100%]: Average Loss = 967.95
Finished [100%]: Average Loss = 1,099.6
Finished [100%]: Average Loss = 1,043
Finished [100%]: Average Loss = 1,144.6
Finished [100%]: Average Loss = 1,204.1
Finished [100%]: Average Loss = 1,049.1
Finished [100%]: Average Loss = 1,264.5
Finished [100%]: Average Loss = 1,238.2
Finished [100%]: Average Loss = 1,136.2
Finished [100%]: Average Loss = 1,083.3
Finished [100%]: Average Loss = 1,069.8
Finished [100%]: Average Loss = 988.8
Finished [100%]: Average Loss = 1,015.1
Finished [100%]: Average Loss = 957.88
Finished [100%]: Average Loss = 970.57
Finished [100%]: Average Loss = 881.36
Finished [100%]: Average Loss = 925.92
Finished [100%]: Average Loss = 991.6
Finished [100%]: Average Loss = 993.04
Finished [100%]: Average Loss = 995.78
Finished [100%]: Average Loss = 973.86
Finished [100%]: Average Loss = 1,068.8
Finished [100%]: Average Loss = 1,180.4
Finished [100%]: Average Loss = 1,133.1
Finished [100%]: Average Loss = 1,234.6
Finished [100%]: Average Loss = 1,267.6
Finished [100%]: Average Loss = 1,172.5
Finished [100%]: Average Loss = 1,294
Finished [100%]: Average Loss = 1,201.8
Finished [100%]: Average Loss = 1,048.6
Finished [100%]: Average Loss = 1,287.1
Finished [100%]: Average Loss = 1,062.5
Finished [100%]: Average Loss = 1,193.8
Finished [100%]: Average Loss = 1,309.2
Finished [100%]: Average Loss = 1,211.1
Finished [100%]: Average Loss = 1,108.7
Finished [100%]: Average Loss = 1,215.9
Finished [100%]: Average Loss = 1,110.3
Finished [100%]: Average Loss = 765.34
Finished [100%]: Average Loss = 591.41
Finished [100%]: Average Loss = 1,024.5
Finished [100%]: Average Loss = 1,047.6
Finished [100%]: Average Loss = 1,104
Finished [100%]: Average Loss = 1,238.1
Finished [100%]: Average Loss = 1,208.9
Finished [100%]: Average Loss = 1,135.6
Finished [100%]: Average Loss = 1,205.6
Finished [100%]: Average Loss = 1,341
Finished [100%]: Average Loss = 1,087.4
Finished [100%]: Average Loss = 1,266.8
Finished [100%]: Average Loss = 1,165.3
Finished [100%]: Average Loss = 1,266.9
Finished [100%]: Average Loss = 1,198.8
Finished [100%]: Average Loss = 1,262.4
Finished [100%]: Average Loss = 992.67
Finished [100%]: Average Loss = 1,095.4
Finished [100%]: Average Loss = 1,229.2
Finished [100%]: Average Loss = 1,055.4
Finished [100%]: Average Loss = 1,164.1
Finished [100%]: Average Loss = 1,184.5
Finished [100%]: Average Loss = 1,039.6
Finished [100%]: Average Loss = 1,048.7
Finished [100%]: Average Loss = 1,165
Finished [100%]: Average Loss = 1,188.6
Finished [100%]: Average Loss = 799.41

Total time: 1069.3 seconds
Weeks fit: 391
Weeks skipped: 0

In [6]:
weeklyBetaEuropeDF = pd.DataFrame(weeklyBetaResultsEurope)
print(weeklyBetaEuropeDF.shape)
weeklyBetaEuropeDF.head(10)

(16031, 5)

                    week  region                 country  betaMean   betaStd
0  2018-01-01/2018-01-07  Europe                 Albania  0.060609  1.077021
1  2018-01-01/2018-01-07  Europe                 Austria  0.047717  1.024270
2  2018-01-01/2018-01-07  Europe                 Belarus -0.854684  0.394496
3  2018-01-01/2018-01-07  Europe                 Belgium  0.111869  1.089182
4  2018-01-01/2018-01-07  Europe  Bosnia and Herzegovina -0.013890  1.032200
5  2018-01-01/2018-01-07  Europe                Bulgaria  0.906500  0.255152
6  2018-01-01/2018-01-07  Europe                 Croatia  0.065730  1.039528
7  2018-01-01/2018-01-07  Europe                  Cyprus  0.087175  1.079257
8  2018-01-01/2018-01-07  Europe          Czech Republic  0.085987  1.057294
9  2018-01-01/2018-01-07  Europe                 Denmark  0.031707  1.141569

In [7]:
weeklyBetaEuropeDF.to_csv('../Data/Processed/weeklyBetaEurope.csv', index=False)